### ISSUE TITLE
Fresh install of Jenkins instance fails

### ISSUE THREAD

**Issue by rothwerx** [jenkinsci/kubernetes-operator#1069]
**Describe the bug**
Following the documentation to install the operator using YAMLs and then using the example yaml to deploy a jenkins instance doesn't work.

**To Reproduce**
Install the latest operator jenkins-operator-0.8.1 and then use the example Jenkins master manifest here https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/deploying-jenkins/ 

**Additional information**
I noticed 0.8.1 updated some things here https://github.com/jenkinsci/kubernetes-operator/pull/1022 but even bumping the Jenkins version in the example manifest to match didn't resolve the issue.

Kubernetes version: v1.31.1 
Jenkins Operator version: v0.8.1 

Add error logs about the problem here (operator logs and Kubernetes events).
```
Will install new plugin plain-credentials 183.va_de8f1dd5a_2b_
Will install new plugin bouncycastle-api 2.30.1.78.1-248.ve27176eb_46cb_
Will install new plugin jaxb 2.3.9-1
Will install new plugin git 5.2.2
Will install new plugin bootstrap5-api 5.3.3-1
Will install new plugin workflow-durable-task-step 1371.vb_7cec8f3b_95e
Will install new plugin authentication-tokens 1.119.v50285141b_7e1
Will install new plugin ssh-credentials 343.v884f71d78167
Will install new plugin cloudbees-folder 6.928.v7c780211d66e
Will install new plugin durable-task 577.v2a_8a_4b_7c0247
Will install new plugin workflow-job 1400.v7fd111b_ec82f
Will install new plugin workflow-basic-steps 1058.vcb_fc1e3a_21a_9
Will install new plugin structs 338.v848422169819
Will install new plugin apache-httpcomponents-client-4-api 4.5.14-208.v438351942757
Will install new plugin workflow-cps 3975.v567e2a_1ffa_22
Will install new plugin ionicons-api 74.v93d5eb_813d5f
Will install new plugin prism-api 1.29.0-17
Will install new plugin commons-lang3-api 3.17.0-84.vb_b_938040b_078
Will install new plugin display-url-api 2.204.vf6fddd8a_8b_e9
Will install new plugin script-security 1365.v4778ca_84b_de5
Will install new plugin branch-api 2.1178.v969d9eb_c728e
Will install new plugin workflow-api 1336.vee415d95c521

Security warnings:
credentials (1380.va_435002fa_924): SECURITY-3373 Encrypted values of credentials revealed to users with Extended Read permission https://www.jenkins.io/security/advisory/2024-10-02/#SECURITY-3373
io.jenkins.tools.pluginmanager.impl.AggregatePluginPrerequisitesNotMetException: Multiple plugin prerequisites not met:
Plugin git:5.2.2 (via credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defined on the top level - configuration-as-code:1810.v9b_c30a_249a_4c,
Plugin kubernetes:4246.v5a_12b_1fe120e (via credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defined on the top level - configuration-as-code:1810.v9b_c30a_249a_4c,
Plugin kubernetes-credentials-provider:1.262.v2670ef7ea_0c5 (via credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defined on the top level - configuration-as-code:1810.v9b_c30a
_249a_4c,
Plugin workflow-aggregator:596.v8c21c963d92d (via pipeline-input-step:495.ve9c153f6067b_->credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defined on the top level - configurat
ion-as-code:1810.v9b_c30a_249a_4c
    at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:240)
    at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:189)
    at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:60)
    Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin git:5.2.2 (via credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defined on the top level -
 configuration-as-code:1810.v9b_c30a_249a_4c
        at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1145)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:701)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:232)
        ... 2 more
    Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin kubernetes:4246.v5a_12b_1fe120e (via credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defi
ned on the top level - configuration-as-code:1810.v9b_c30a_249a_4c
        at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1145)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:701)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:232)
        ... 2 more
    Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin kubernetes-credentials-provider:1.262.v2670ef7ea_0c5 (via credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is
an older version defined on the top level - configuration-as-code:1810.v9b_c30a_249a_4c
        at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1145)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:701)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:232)
        ... 2 more
    Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin workflow-aggregator:596.v8c21c963d92d (via pipeline-input-step:495.ve9c153f6067b_->credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4
a_122a_a_e, but there is an older version defined on the top level - configuration-as-code:1810.v9b_c30a_249a_4c
        at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1145)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:701)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:232)
        ... 2 more
Multiple plugin prerequisites not met:
Plugin git:5.2.2 (via credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defined on the top level - configuration-as-code:1810.v9b_c30a_249a_4c,
Plugin kubernetes:4246.v5a_12b_1fe120e (via credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defined on the top level - configuration-as-code:1810.v9b_c30a_249a_4c,
Plugin kubernetes-credentials-provider:1.262.v2670ef7ea_0c5 (via credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defined on the top level - configuration-as-code:1810.v9b_c30a
_249a_4c,
Plugin workflow-aggregator:596.v8c21c963d92d (via pipeline-input-step:495.ve9c153f6067b_->credentials:1380.va_435002fa_924) depends on configuration-as-code:1836.vccda_4a_122a_a_e, but there is an older version defined on the top level - configurat
ion-as-code:1810.v9b_c30a_249a_4c
```

**Comment by brokenpip3** [comment]
yeah the issue is quite simple, you need to specify the correct configuration-as-code version, let me update the repo with that and the new jenkins version, but in the mean time you can quickly fix it

**Comment by nobeler** [comment]
I think it dose not  fix,  I get a same type wrong: https://github.com/jenkinsci/kubernetes-operator/issues/1077
