### ISSUE TITLE
Jenkins Mater POD unable to start

### ISSUE THREAD

**Issue by pmondal08** [jenkinsci/kubernetes-operator#125]
Hey Guys,

The operator been working fine for me till today. But starting today after redeploying the operator in a new cluster i am getting following error. I have tested in different environments. And even reduced the Jenkins docker images to my earlier working image. but same issue, is it me or the plugins not supported any more?

2019-10-07 11:11:55.777+0000 [id=28]    INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2019-10-07 11:11:55.842+0000 [id=27]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jenkins Git client plugin v2.9.0 (git-client)
java.io.IOException: Jenkins Git client plugin version 2.9.0 failed to load.
 - Configuration as Code Plugin version 1.29 is older than required. To fix, install version 1.30 or later.
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:922)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:545)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1118)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-10-07 11:11:55.842+0000 [id=27]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jenkins GIT server Plugin v1.8 (git-server)
java.io.IOException: Jenkins GIT server Plugin version 1.8 failed to load.
 - Jenkins Git client plugin version 2.9.0 failed to load. Fix this plugin first.
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:922)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:545)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1118)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)

**Comment by pmondal08** [comment]
I fixed it at my end. its the configuration as code plugin in base_plugins.go i bumped it to 1.30.

**Comment by pniederlag** [comment]
It should be possible to adapt versions of base plugins via _yaml_ for _kind: Jenkins_ with **spec.master.basePlugins**

    basePlugins:
    - name: configuration-as-code
      version: "1.30"

**Comment by pmondal08** [comment]
Closing the issue!!
