### ISSUE TITLE
Problem with getting it (at least the readme example) running

### ISSUE THREAD

**Issue by BogdanSorlea** [jenkinsci/kubernetes-operator#128]
Hey,

So I am experiencing a weird situation where I am trying to run the setup in the example (in the README) and yet the pod keeps getting killed and I am not sure why. I even tried increasing the initialDelaySeconds of the readinessProbe - and that changed the behaviour - but it still kills the pod.

list of events as returned by `kubectl get events --sort-by=.metadata.creationTimestamp` when readinessProbe.initialDelaySeconds=30:
```
7m3s        Normal    Scheduled                 pod/jenkins-example                      Successfully assigned default/jenkins-example to docker-desktop
7m2s        Normal    Pulling                   pod/jenkins-example                      Pulling image "jenkins/jenkins:lts"
7m1s        Normal    Pulled                    pod/jenkins-example                      Successfully pulled image "jenkins/jenkins:lts"
7m1s        Normal    Created                   pod/jenkins-example                      Created container jenkins-master
7m1s        Normal    Started                   pod/jenkins-example                      Started container jenkins-master
6m24s       Warning   Unhealthy                 pod/jenkins-example                      Readiness probe failed: HTTP probe failed with statuscode: 503
6m12s       Normal    Killing                   pod/jenkins-example                      Stopping container jenkins-master
6m3s        Normal    Scheduled                 pod/jenkins-example                      Successfully assigned default/jenkins-example to docker-desktop
6m2s        Normal    Pulling                   pod/jenkins-example                      Pulling image "jenkins/jenkins:lts"
6m1s        Normal    Pulled                    pod/jenkins-example                      Successfully pulled image "jenkins/jenkins:lts"
6m1s        Normal    Started                   pod/jenkins-example                      Started container jenkins-master
6m1s        Normal    Created                   pod/jenkins-example                      Created container jenkins-master
5m26s       Warning   Unhealthy                 pod/jenkins-example                      Readiness probe failed: HTTP probe failed with statuscode: 503
5m17s       Normal    Killing                   pod/jenkins-example                      Stopping container jenkins-master
```
vs
list of events returned by same command when readinessProbe.initialDelaySeconds=90:
```
6m40s       Normal    Scheduled                 pod/jenkins-example                      Successfully assigned default/jenkins-example to docker-desktop
6m38s       Normal    Created                   pod/jenkins-example                      Created container jenkins-master
6m38s       Normal    Pulled                    pod/jenkins-example                      Successfully pulled image "jenkins/jenkins:lts"
6m38s       Normal    Started                   pod/jenkins-example                      Started container jenkins-master
6m10s       Normal    Killing                   pod/jenkins-example                      Stopping container jenkins-master
5m8s        Normal    Scheduled                 pod/jenkins-example                      Successfully assigned default/jenkins-example to docker-desktop
5m7s        Normal    Pulling                   pod/jenkins-example                      Pulling image "jenkins/jenkins:lts"
5m6s        Normal    Created                   pod/jenkins-example                      Created container jenkins-master
5m6s        Normal    Pulled                    pod/jenkins-example                      Successfully pulled image "jenkins/jenkins:lts"
5m5s        Normal    Started                   pod/jenkins-example                      Started container jenkins-master
3m2s        Normal    Killing                   pod/jenkins-example                      Stopping container jenkins-master
```

In the logs the only weird thing is these SEVERE errors:
```
java.io.IOException: Jenkins Git client plugin version 2.9.0 failed to load.
 - Configuration as Code Plugin version 1.29 is older than required. To fix, install version 1.30 or later.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:922)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:545)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1118)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-08 09:45:04.759+0000 [id=28]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jenkins Git plugin v3.12.0 (git)
java.io.IOException: Jenkins Git plugin version 3.12.0 failed to load.
 - Jenkins Git client plugin version 2.9.0 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:922)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:545)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1118)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-08 09:45:04.772+0000 [id=25]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jenkins GIT server Plugin v1.8 (git-server)
java.io.IOException: Jenkins GIT server Plugin version 1.8 failed to load.
 - Jenkins Git client plugin version 2.9.0 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:922)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:545)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1118)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-08 09:45:04.774+0000 [id=26]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Shared Groovy Libraries v2.15 (workflow-cps-global-lib)
java.io.IOException: Pipeline: Shared Groovy Libraries version 2.15 failed to load.
 - Jenkins GIT server Plugin version 1.8 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:922)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:545)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1118)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-08 09:45:04.775+0000 [id=26]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Declarative v1.3.9 (pipeline-model-definition)
java.io.IOException: Pipeline: Declarative version 1.3.9 failed to load.
 - Pipeline: Shared Groovy Libraries version 2.15 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:922)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:545)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1118)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-08 09:45:04.780+0000 [id=28]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline v2.6 (workflow-aggregator)
java.io.IOException: Pipeline version 2.6 failed to load.
 - Pipeline: Shared Groovy Libraries version 2.15 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:922)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:545)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1118)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
but then the log reports (all good, later followed by JVM terminating):
```
2019-10-08 09:45:16.318+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
2019-10-08 09:45:16.398+0000 [id=19]	INFO	hudson.WebAppMain$3#run: Jenkins is fully up and running
2019-10-08 09:45:20.647+0000 [id=46]	INFO	hudson.model.UpdateSite#updateData: Obtained the latest update center data file for UpdateSource default
2019-10-08 09:45:21.573+0000 [id=46]	INFO	h.m.DownloadService$Downloadable#load: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller
2019-10-08 09:45:22.542+0000 [id=46]	INFO	h.m.DownloadService$Downloadable#load: Obtained the updated data file for hudson.tools.JDKInstaller
2019-10-08 09:45:22.543+0000 [id=46]	INFO	hudson.util.Retrier#start: Performed the action check updates server successfully at the attempt #1
2019-10-08 09:45:22.591+0000 [id=46]	INFO	hudson.model.AsyncPeriodicWork$1#run: Finished Download metadata. 8,156 ms
2019-10-08 09:46:36.212+0000 [id=21]	INFO	winstone.Logger#logInternal: JVM is terminating. Shutting down Jetty
```

I can also confirm that in the second case (readinessProbe.initialDelaySeconds=90 - where events do not report a 503 response given to the readinessProbe, according to my logs above), the timestamps kind of correlate to the time values given to readinessProbe, e.g.:
```
Events:
  Type    Reason     Age   From                     Message
  ----    ------     ----  ----                     -------
  Normal  Scheduled  106s  default-scheduler        Successfully assigned default/jenkins-example to docker-desktop
  Normal  Pulling    105s  kubelet, docker-desktop  Pulling image "jenkins/jenkins:lts"
  Normal  Pulled     104s  kubelet, docker-desktop  Successfully pulled image "jenkins/jenkins:lts"
  Normal  Created    104s  kubelet, docker-desktop  Created container jenkins-master
  Normal  Started    104s  kubelet, docker-desktop  Started container jenkins-master
  Normal  Killing    4s    kubelet, docker-desktop  Stopping container jenkins-master
```
logs just above are corresponding to the following configuration:
```
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 90
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      livenessProbe:
        initialDelaySeconds: 120
```

So my only hypothesis is that possibly the SEVERE errors are sending a kill command to k8s, to kill the pod - but it only gets in effect after the readinessProbe kicks into action (even if it probably does not fail(?)). Or some other hidden reason.

Can anyone check what is going on? I'm running out of ideas

**Comment by tomaszsek** [comment]
Hi @BogdanSorlea

Please look at my comment https://github.com/jenkinsci/kubernetes-operator/issues/126#issuecomment-539461440.

Cheers
