### ISSUE TITLE
Q: How to authenticate to https?

### ISSUE THREAD

**Issue by elfhack** [jenkinsci/kubernetes-operator#14]
Our pods don't have ssh access, and we've been unsuccessfully trying to seed our jobs from a private bitbucket repo. How would one use secrets in this case?

Our deployment looks like this
```
apiVersion: jenkins.io/v1alpha1
kind: Jenkins
metadata:
  name: GS
  namespace: jenkins
spec:
  master:
   image: jenkins/jenkins
  seedJobs:
  - id: GS
    targets: "cicd/jobs/*.jenkins"
    description: "GS Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://user:pass@bitbucket.org/somerepo/test.git
```

And this is what jenkins does with it

```
Started
Running as SYSTEM
Building in workspace /var/jenkins/home/workspace/GS-job-dsl-seed
Cloning the remote Git repository
Using shallow clone
Avoid fetching tags
Cloning repository https://user:pass@bitbucket.org/somerepo/test.git
 > git init /var/jenkins/home/workspace/GS-job-dsl-seed # timeout=10
Fetching upstream changes from https://user@bitbucket.org/somerepo/test.git
 > git --version # timeout=10
using GIT_SSH to set credentials Greensteam
 > git fetch --no-tags --progress https://user@bitbucket.org/somerepo/test.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --no-tags --progress https://user@bitbucket.org/somerepo/test.git +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 128:
stdout: 
stderr: remote: Invalid username or password
fatal: Authentication failed for 'https://user@bitbucket.org/somerepo/test.git/'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2042)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1761)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$400(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:442)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:655)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
	at hudson.scm.SCM.checkout(SCM.java:504)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1816)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: Error cloning remote repo 'origin'
Finished: FAILURE
```

**Comment by tomaszsek** [comment]
Generate SSH key https://confluence.atlassian.com/bitbucket/set-up-an-ssh-key-728138079.html.
Add public key to BitBucket repository `SSH Keys`:
![image](https://user-images.githubusercontent.com/31410181/54136314-d7646f00-441b-11e9-8f0d-2943dbec043f.png)
Configure seed job to use SSH URL and put private key in Kubernetes secret https://github.com/jenkinsci/kubernetes-operator/blob/master/docs/getting-started.md#configure-seed-jobs.

**Comment by elfhack** [comment]
Well that's the problem - we can't use ssh, since our pods only can communicate over 80 and 443 to the internet, hence we need to use http(s). I took a look at the source code and see that you expect a ssh key when using privateKey. Any chance we could use a user/pass secret like you create for the admin user of jenkins master?

**Comment by tomaszsek** [comment]
I've checked it is possible to add Jenkins credentials as Username/Password with BitBucket user name and BitBucket `App password`. We can add option to seed job config to use username/password as credentials. Similar to SSH private key user/pass should be keep in Kubernetes secret.

**Comment by elfhack** [comment]
Yes, this would be exactly what we need

**Comment by tomaszsek** [comment]
Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.0.8
