### ISSUE TITLE
Jenkins pod authentication errors for jenkins-operator user after start-up (config includes LDAP security realm)

### ISSUE THREAD

**Issue by BogdanSorlea** [jenkinsci/kubernetes-operator#208]
if using the Jenkins LDAP plugin and configuring it to connect to a valid LDAP server I see the following error (in the logs of the jenkins pod (not the operator)):
```
Nov 19, 2019 5:22:46 PM jenkins.security.BasicHeaderApiTokenAuthenticator authenticate
WARNING: API token matched for user jenkins-operator but the impersonation failed
org.acegisecurity.userdetails.UsernameNotFoundException: User jenkins-operator not found in directory.
	at org.acegisecurity.ldap.search.FilterBasedLdapUserSearch.searchForUser(FilterBasedLdapUserSearch.java:126)
	at hudson.security.LDAPSecurityRealm$LDAPUserDetailsService.loadUserByUsername(LDAPSecurityRealm.java:1314)
	at hudson.security.LDAPSecurityRealm$LDAPUserDetailsService.loadUserByUsername(LDAPSecurityRealm.java:1251)
	at jenkins.security.ImpersonatingUserDetailsService.loadUserByUsername(ImpersonatingUserDetailsService.java:30)
	at hudson.model.User.getUserDetailsForImpersonation(User.java:394)
	at jenkins.security.BasicHeaderApiTokenAuthenticator.authenticate(BasicHeaderApiTokenAuthenticator.java:35)
[...]
```
I have a feeling that it's probably the operator trying to authenticate(?) and that because of it there might be negative side-effects (which I am not necessarily seeing locally, but I do get a complete failure of the jenkins pod when deployed to our target k8s cluster - not sure if related, though).

How worried should I be and what should I do about it?

**Comment by tomaszsek** [comment]
Hi @BogdanSorlea,

Did you set up everything as described in #133?
It looks like your LDAP server doesn't contains user `jenkins-operator` for the operator itself. 

Cheers

**Comment by BogdanSorlea** [comment]
I hereby confirm that the problem was fixed based on the indications in https://github.com/jenkinsci/kubernetes-operator/issues/133
Closing issue.
