### ISSUE TITLE
Not able to create a new jenkins servers failing during the backup container creationg

### ISSUE THREAD

**Issue by riqtest01** [jenkinsci/kubernetes-operator#398]
# Expected Behavior
jenkins should be up
# Actual Behavior
jenkins pod is not coming up as it is failing to create the backup container 
# Steps to Reproduce the Problem
Container 'jenkins-master' is terminated, status '{Name:jenkins-master State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:1,Signal:0,Reason:Error,Message:,StartedAt:2020-05-20 16:20:34 +0000 UTC,FinishedAt:2020-05-20 16:21:30 +0000 UTC,ContainerID:docker://87c17cafc37d996de2a6e5d84380d78de3e586c2b48ae281f07313cd4d30487c,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:jenkins/jenkins:2.204.5 ImageID:docker-pullable://jenkins/jenkins@sha256:7ea1d29c621a10d1e231013f62e32f0eb726dde15a4c219e5010564a6766daa8 ContainerID:docker://87c17cafc37d996de2a6e5d84380d78de3e586c2b48ae281f07313cd4d30487c}'	{"cr": "riq-stg-master01"}
1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Jenkins Operator version:

```
  (paste your output here)
  ```

**Comment by riqtest01** [comment]
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: master01
spec:
  master:
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    plugins:
    - name: simple-theme-plugin
      version: "0.6"
    basePlugins:
    - name: kubernetes
      version: "1.24.1"
    - name: workflow-job
      version: "2.37"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.2.2"
    - name: job-dsl
      version: "1.77"
    - name: command-launcher
      version: "1.4"
    - name: configuration-as-code
      version: "1.36"
    - name: configuration-as-code-support
      version: "1.19"
    - name: kubernetes-credentials-provider
      version: "0.13"
    - name: nodejs
      version: "1.3.4"
    - name: bitbucket
      version: "1.1.11"
    - name: aws-bucket-credentials
      version: "1.0.0"
    - name: s3
      version: "0.11.5"
    - name: aws-credentials
      version: "1.28"
    - name: pipeline-aws
      version: "1.41"
    - name:  jenkins-multijob-plugin
      version: "1.32"
    - name:  jobConfigHistory
      version: "2.25"
    - name:  git-parameter
      version: "0.9.12"
    - name:  matrix-auth
      version: "2.5"
    - name:  github-api
      version: "1.106"
    - name:  build-name-setter
      version: "2.10"
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:2.204.5
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
    - name: backup # container responsible for the backup and restore
      env:
      - name: BACKUP_DIR
        value: /backup
      - name: JENKINS_HOME
        value: /jenkins-home
      - name: BACKUP_COUNT
        value: "3" # keep only the 2 most recent backups
      image: virtuslab/jenkins-operator-backup-pvc:v0.0.7 # look at backup/pvc directory
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /jenkins-home # Jenkins home volume
        name: jenkins-home
      - mountPath: /backup # backup volume
        name: backup
    volumes:
    - name: backup # PVC volume where backups will be stored
      persistentVolumeClaim:
        claimName: master-backup
  backup:
    containerName: backup # container name is responsible for backup
    action:
      exec:
        command:
        - /home/user/bin/backup.sh # this command is invoked on "backup" container to make backup, for example /home/user/bin/backup.sh <backup_number>, <backup_number> is passed by operator
    interval: 7200 # how often make backup in seconds
    makeBackupBeforePodDeletion: true # make a backup before pod deletion
  restore:
    containerName: backup # container name is responsible for restore backup
    action:
      exec:
        command:
        - /home/user/bin/restore.sh # this command is invoked on "backup" container to make restore backup, for example /home/user/bin/restore.sh <backup_number>, <backup_number> is passed by operator
    #recoveryOnce: <backup_number> # if want to restore specific backup configure this field and then Jenkins will be restarted and desired backup will be restored
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    credentialType: usernamePassword
    credentialID: github-staging
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/riqtest01/riq-stg-jenkins-pipeline-jobs.git

**Comment by riqtest01** [comment]
Also tried with base jenkins operator and it is also failing. I am trying to use jenkins/jenkins:2.204.5 as we are still using the older jenkins operator

2020-05-20T18:09:07.100Z	INFO	controller-jenkins	base/reconcile.go:470	Jenkins master pod restarted by kubernetes: Invalid Jenkins pod phase '{Phase:Failed Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-05-20 18:07:24 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-05-20 18:07:24 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [jenkins-master]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-05-20 18:07:24 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [jenkins-master]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-05-20 18:07:24 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:192.168.65.3 PodIP:10.1.0.155 StartTime:2020-05-20 18:07:24 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:jenkins-master State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:137,Signal:0,Reason:Error,Message:,StartedAt:2020-05-20 18:07:26 +0000 UTC,FinishedAt:2020-05-20 18:09:05 +0000 UTC,ContainerID:docker://892f8eca2ca3f5a6107a8f0bdcfdd1bfc4ee4ca7e8866d9a276faf113572f1f6,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:jenkins/jenkins:2.204.5 ImageID:docker-pullable://jenkins/jenkins@sha256:7ea1d29c621a10d1e231013f62e32f0eb726dde15a4c219e5010564a6766daa8 ContainerID:docker://892f8eca2ca3f5a6107a8f0bdcfdd1bfc4ee4ca7e8866d9a276faf113572f1f6}] QOSClass:Burstable}'	{"cr": "example"}
2020-05-20T18:09:07.388Z	INFO	controller-jenkins	base/reconcile.go:415	Creating a new Jenkins Master Pod default/jenkins-example	{"cr": "example"}

apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
spec:
  master:
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:2.204.5
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git

**Comment by tomaszsek** [comment]
Hi @riqtest01,

Please look at the Jenkins master container logs.

Cheers

**Comment by riqio** [comment]
hi @tomaszsek 
Pod just gets on terminating and recreating 

2020-05-22T00:23:13.566Z	INFO	controller-jenkins	base/reconcile.go:415	Creating a new Jenkins Master Pod default/jenkins-example	{"cr": "example"}
2020-05-22T00:24:41.699Z	INFO	controller-jenkins	base/reconcile.go:470	Jenkins master pod restarted by kubernetes: Invalid Jenkins pod phase '{Phase:Failed Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-05-22 00:23:13 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-05-22 00:23:13 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [jenkins-master]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-05-22 00:23:13 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [jenkins-master]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-05-22 00:23:13 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:192.168.65.3 PodIP:10.1.0.243 StartTime:2020-05-22 00:23:13 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:jenkins-master State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:137,Signal:0,Reason:Error,Message:,StartedAt:2020-05-22 00:23:15 +0000 UTC,FinishedAt:2020-05-22 00:24:40 +0000 UTC,ContainerID:docker://78f590b314966caa333a797e122700d28fc19151b354f45518f0372b6e9d7d08,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:jenkins/jenkins:lts ImageID:docker-pullable://jenkins/jenkins@sha256:15fca69266f4cc2107449d9fa2595acf0cbe1584eb425ee6f2fe9cefc9fc4b97 ContainerID:docker://78f590b314966caa333a797e122700d28fc19151b354f45518f0372b6e9d7d08}] QOSClass:Burstable}'	{"cr": "example"}
2020-05-22T00:24:42.336Z	INFO	controller-jenkins	base/reconcile.go:415	Creating a new Jenkins Master Pod default/jenkins-example	{"cr": "example"}

Attaching the logs from jenkins-master 

[jenkins-master.txt](https://github.com/jenkinsci/kubernetes-operator/files/4665423/jenkins-master.txt)

**Comment by InhexSTER** [comment]
My backup pod fails with find: '/backup/lost+found': Permission denied
That folder is created automatically by ext4 I think in this case

**Comment by tomaszsek** [comment]
Please use `virtuslab/jenkins-operator-backup-pvc:v0.0.8` backup Docker image.

**Comment by jtgans** [comment]
Also having this issue in production with exactly the same error on GKE using Filestore (fancy name for NFS) as the PV.

**Comment by jtgans** [comment]
FYI: Worked around the issue by setting up the volumes: stanza like this:

```
        volumeMounts:
          - mountPath: /jenkins-home
            name: jenkins-home
          - mountPath: /backup
            subPath: backups
            name: backup
```

The error in the Docker container still persists in v0.1.0. @tomaszsek, it would greatly help in debugging this if you could provide the repository that generates the backups container. I suspect this could easily be fixed by not using bash's braindamaged `set -e`, but I can't provide a PR or diff to fix the script without knowing where the source is.

**Comment by jtgans** [comment]
Found the source, finally, and here's the problem:

https://github.com/jenkinsci/kubernetes-operator/blob/588cc36bc650bf49565c45ab95dbd0fbcecf9fa5/backup/pvc/bin/run.sh#L3

The error is definitely occuring because of `set -e` and `pipefail`. Probably better to remove those options and validate the list of files generated by `find` rather than blindly breaking the script run. Ie:

```bash
while true;
do
    sleep 10
    if [[ ! -z "${BACKUP_COUNT}" ]]; then
        echo "Trimming to only ${BACKUP_COUNT} recent backups in preparation for new backup"
        backup_files=$(find "${BACKUP_DIR}" -name '*.tar.gz' -exec basename '{}' ';' | sort -gr | tail -n +$((BACKUP_COUNT +1)))
        echo "${backup_files}" |xargs -I '{}' rm ${BACKUP_DIR}/'{}' || exit $?
    fi
done
```

**Comment by jtgans** [comment]
Once I fixed that, my Jenkins instance starts, but the Configuration as Code fails to run with this dumped out in the operator logs:

```
2020-06-24T19:49:06.324Z        WARN    controller-jenkins      groovy/groovy.go:57     user-casc Source 'jenkins-mende
l-linux-casc' Name '1-config-as-code.yaml' groovy script execution failed, logs :                                     
java.lang.NoClassDefFoundError: javax/annotation/Nonnull
        at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:1
18)                                                                                                                   
        at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:77)
        at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:267)
        at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.check(DataBoundConfigurator.java:101)
        at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:344)
        at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
        at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:352)
        at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
        at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$7(ConfigurationAsCode.java:743)
        at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:693)
        at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:743)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:728)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:608)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:603)
        at io.jenkins.plugins.casc.ConfigurationAsCode$configureWith$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at Script1.run(Script1.groovy:83)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:623)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:594)
        at hudson.util.RemotingDiagnostics$Script.call(RemotingDiagnostics.java:142)
        at hudson.util.RemotingDiagnostics$Script.call(RemotingDiagnostics.java:114)
        at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
        at hudson.util.RemotingDiagnostics.executeGroovy(RemotingDiagnostics.java:111)
        at jenkins.model.Jenkins._doScript(Jenkins.java:4513)
        at jenkins.model.Jenkins.doScriptText(Jenkins.java:4491)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
        at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
        at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
        at hudson.security.HudsonPrivateSecurityRealm$3.doFilter(HudsonPrivateSecurityRealm.java:947)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
        at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
        at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at jenkins.security.ApiCrumbExclusion.process(ApiCrumbExclusion.java:48)
        at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:127)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
        at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.BasicHeaderProcessor.success(BasicHeaderProcessor.java:139)
        at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:82)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.j
ava:249)                                                                                                              
        at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:500)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.lang.Thread.run(Thread.java:748)
        {"cr": "mendel-linux"}
2020-06-24T19:49:06.324Z        WARN    controller-jenkins      jenkins/jenkins_controller.go:171       Reconcile loop 
failed: script execution failed {"cr": "mendel-linux"}                                                                
```

No idea why `Nonnull` isn't being found here. Something screwball in the way the operator code is running, I suspect. My JCasC code isn't even Groovy code -- it's YAML, so this is actually out of my hands. The Jenkins instance YAML I'm using:

```
---
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: mendel-linux
spec:
  master:
    basePlugins:
      - name: authentication-tokens
        version: "1.4"
      - name: kubernetes
        version: "1.15.10"
      - name: workflow-job
        version: "2.39"
      - name: workflow-aggregator
        version: "2.6"
      - name: git
        version: "4.3.0"
      - name: job-dsl
        version: "1.77"
      - name: configuration-as-code
        version: "1.38"
      - name: configuration-as-code-support
        version: "1.18"
      - name: kubernetes-credentials-provider
        version: "0.15"
      - name: repo
        version: "1.13.0"
    plugins:
      - name: copyartifact
        version: "1.44"
      - name: google-storage-plugin
        version: "1.5.1"
      - name: google-login
        version: "1.6"
      - name: gerrit-code-review
        version: "0.4.4"
      - name: pipeline-utility-steps
        version: "2.6.0"
  seedJobs:
    - id: mendel-linux
      targets: "cicd/jobs/*.jenkins"
      description: "Mendel Linux Jenkins Repository"
      repositoryBranch: "master"
      repositoryUrl: "https://coral.googlesource.com/gke-jenkins.git"
      buildPeriodically: "*/30 * * * *"
  configurationAsCode:
    configurations:
      - name: jenkins-mendel-linux-casc
  master:
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:lts
      - name: backup
        image: virtuslab/jenkins-operator-backup-pvc:v0.0.8
        imagePullPolicy: IfNotPresent
        env:
          - name: BACKUP_DIR
            value: /backup
          - name: JENKINS_HOME
            value: /jenkins-home
          - name: BACKUP_COUNT
            value: "3"
        volumeMounts:
          - mountPath: /jenkins-home
            name: jenkins-home
          - mountPath: /backup
            subPath: backups
            name: backup
    volumes:
      - name: backup
        persistentVolumeClaim:
          claimName: jenkins-backups
  backup:
    containerName: backup
    action:
      exec:
        command:
          - /home/user/bin/backup.sh
    interval: 30
    makeBackupBeforePodDeletion: true
  restore:
    containerName: backup
    action:
      exec:
        command:
          - /home/user/bin/restore.sh
```

Aside from the updated plugins in my instance definition, I'm using the same design as what you have in the current documentation. If I eliminate everything except the backup changes, the pods schedule fine and the configuration gets applied properly.
