### ISSUE TITLE
Seed-job-agent pod CrashLoopBackOff. Cannot Connect

### ISSUE THREAD

**Issue by AaronJaegerVA** [jenkinsci/kubernetes-operator#525]
**Describe the bug**

Seed-job-agent pod will not run properly. Cannot connect to `http://jenkins-operator-http-ets-jenkins-001.jenkins-operator.svc.cluster.local:8080/tcpSlaveAgentListener`

Full error:

```
[root@vac10vchetv601 ~]# k logs -f pod/seed-job-agent-ets-jenkins-001-8885c7496-5kjtw -n jenkins-operator
Mar 08, 2021 2:58:55 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: seed-job-agent
Mar 08, 2021 2:58:55 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Mar 08, 2021 2:58:55 PM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 4.6
Mar 08, 2021 2:58:55 PM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using /home/jenkins/agent/remoting as a remoting work directory
Mar 08, 2021 2:58:55 PM org.jenkinsci.remoting.engine.WorkDirManager setupLogging
INFO: Both error and output logs will be printed to /home/jenkins/agent/remoting
Mar 08, 2021 2:58:55 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://jenkins-operator-http-ets-jenkins-001.jenkins-operator.svc.cluster.local:8080]
Mar 08, 2021 2:59:15 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: Failed to connect to http://jenkins-operator-http-ets-jenkins-001.jenkins-operator.svc.cluster.local:8080/tcpSlaveAgentListener/: jenkins-operator-http-ets-jenkins-001.jenkins-operator.svc.cluster.local
java.io.IOException: Failed to connect to http://jenkins-operator-http-ets-jenkins-001.jenkins-operator.svc.cluster.local:8080/tcpSlaveAgentListener/: jenkins-operator-http-ets-jenkins-001.jenkins-operator.svc.cluster.local
        at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:214)
        at hudson.remoting.Engine.innerRun(Engine.java:689)
        at hudson.remoting.Engine.run(Engine.java:514)
Caused by: java.net.UnknownHostException: jenkins-operator-http-ets-jenkins-001.jenkins-operator.svc.cluster.local
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:211)
        ... 2 more
```

`http://jenkins-operator-http-ets-jenkins-001.jenkins-operator.svc.cluster.local:8080` is resolvable and reachable from another pod in the cluster.

**Additional information**

Kubernetes version: v1.19.x
Jenkins Operator version: v.0.5.0

**Comment by Schnitzel** [comment]
we had the same issue, and in the end it actually wasn't the seed-job-agent the issue, but jenkins itself, solved with https://github.com/jenkinsci/kubernetes-operator/issues/523

**Comment by prryb** [comment]
Closing, solution: https://github.com/jenkinsci/kubernetes-operator/issues/523
