### ISSUE TITLE
jenkins-deploy-test crash loopback 

### ISSUE THREAD

**Issue by matty1979** [jenkinsci/kubernetes-operator#526]
**Describe the bug**
jenkins-deploy-test pod crash loopback 

**To Reproduce**
installed crd and all-in-one-v1alpha2 

**Additional information**
java.io.IOException: Failed to load: Credentials Plugin (2.3.15)
Kubernetes version:
Jenkins Operator version:

Add error logs about the problem here (operator logs and Kubernetes events).
```
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2021-03-08 19:15:56.161+0000 [id=27] SEVERE jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Kubernetes plugin v1.28.6 (kubernetes)
java.io.IOException: Failed to load: Kubernetes plugin (1.28.6)
- Failed to load: Authentication Tokens API Plugin (1.4)
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
at hudson.PluginManager$2$1$1.run(PluginManager.java:549)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2021-03-08 19:15:56.162+0000 [id=27] SEVERE jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Kubernetes Credentials Provider v0.15 (kubernetes-credentials-provider)
java.io.IOException: Failed to load: Kubernetes Credentials Provider (0.15)
- Failed to load: Credentials Plugin (2.3.15)
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
at hudson.PluginManager$2$1$1.run(PluginManager.java:549)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2021-03-08 19:16:00.175+0000 [id=27] INFO jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2021-03-08 19:16:00.190+0000 [id=27] INFO jenkins.InitReactorRunner$1#onAttained: Started all plugins
2021-03-08 19:16:02.014+0000 [id=27] INFO jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2021-03-08 19:16:02.419+0000 [id=26] INFO jenkins.InitReactorRunner$1#onAttained: System config loaded
2021-03-08 19:16:02.677+0000 [id=29] INFO jenkins.InitReactorRunner$1#onAttained: System config adapted
2021-03-08 19:16:02.678+0000 [id=29] INFO jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2021-03-08 19:16:02.678+0000 [id=28] INFO jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
2021-03-08 19:16:02.683+0000 [id=29] INFO j.util.groovy.GroovyHookScript#execute: Executing /var/lib/jenkins/init.groovy.d/createOperatorUser.groovy
2021-03-08 19:16:02.698+0000 [id=43] INFO hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started Download metadata
2021-03-08 19:16:02.731+0000 [id=43] INFO hudson.util.Retrier#start: Attempt #1 to do the action check updates server
Logs from 3/8/2021, 2:15:38 PM
Show timestamps
Show previous terminated container
```

```
- Failed to load: Credentials Plugin (2.3.15)
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
at hudson.PluginManager$2$1$1.run(PluginManager.java:549)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by Schnitzel** [comment]
I had the same issue and solved it via https://github.com/jenkinsci/kubernetes-operator/issues/523

**Comment by prryb** [comment]
Closing, solution: https://github.com/jenkinsci/kubernetes-operator/issues/523
