### ISSUE TITLE
Configuration as Code plugin update required 1.46 -> 1.47

### ISSUE THREAD

**Issue by dlucasd** [jenkinsci/kubernetes-operator#540]
Hi,

I followed the Getting Started guide to set up a jenkins in my local kubernetes.

My jenkins pod restarts indefinitly.

To reproduce this error, just follow the guide in the documentation.

I've changed the basePlugins parameters to use the v1.47 conf as code plugin and it works well!
```
    basePlugins:
    - name: kubernetes
      version: "1.28.6"
    - name: workflow-job
      version: "2.40"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.5.0"
    - name: job-dsl
      version: "1.77"
    **- name: configuration-as-code
      version: "1.47"**
    - name: kubernetes-credentials-provider
      version: "0.15"
```

Kubernetes version: 1.19
Jenkins Operator version: 0.5.0

Error logs :
```
2021-04-09 14:43:44.506+0000 [id=27]    INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2021-04-09 14:43:44.547+0000 [id=26]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Credentials Plugin v2.3.15 (credentials)
java.io.IOException: Failed to load: Credentials Plugin (2.3.15)
 - Update required: Configuration as Code Plugin (1.46) to be updated to 1.47 or higher
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:549)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Thanks

**Comment by dlucasd** [comment]
duplicate issue : #523
sorry
