### ISSUE TITLE
Development instructions don't result in successful build

### ISSUE THREAD

**Issue by benlangfeld** [jenkinsci/kubernetes-operator#57]
```
➭ make minikube-run EXTRA_ARGS='--minikube --local'
+ minikube-start
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.102
+ deepcopy-gen
operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [jenkins:[v1alpha1 v1alpha2], ]
F0715 20:35:41.620683   26233 deepcopy.go:922] Hit an unsupported type invalid type for *invalid type
goroutine 1 [running]:
k8s.io/klog.stacks(0xc0002be100, 0xc00051c240, 0x66, 0xb6)
	pkg/mod/k8s.io/klog@v0.3.1/klog.go:855 +0xb1
k8s.io/klog.(*loggingT).output(0x3ffc080, 0xc000000003, 0xc000341810, 0x3e3ba04, 0xb, 0x39a, 0x0)
	pkg/mod/k8s.io/klog@v0.3.1/klog.go:806 +0x2d9
k8s.io/klog.(*loggingT).printf(0x3ffc080, 0x3, 0x29b1ac6, 0x21, 0xc00065aca0, 0x2, 0x2)
	pkg/mod/k8s.io/klog@v0.3.1/klog.go:705 +0x14e
k8s.io/klog.Fatalf(...)
	pkg/mod/k8s.io/klog@v0.3.1/klog.go:1256
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).doPointer(0xc000597a80, 0xc000360840, 0xc0006bbcc0)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:922 +0x3c1
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).generateFor(0xc000597a80, 0xc000360840, 0xc0006bbcc0)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:695 +0xc5
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).doStruct(0xc000597a80, 0xc0003606e0, 0xc0006bbcc0)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:865 +0x472
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).generateFor(0xc000597a80, 0xc0003606e0, 0xc0006bbcc0)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:695 +0xc5
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).GenerateType(0xc000597a80, 0xc0006bce40, 0xc0003606e0, 0x2c99d40, 0xc00052f780, 0x0, 0x29995d9)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:608 +0xe86
k8s.io/gengo/generator.(*Context).executeBody(0xc0006bce40, 0x2c968c0, 0xc0006d8c00, 0x2d0f5a0, 0xc000597a80, 0x60, 0x10)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/generator/execute.go:304 +0x11d
k8s.io/gengo/generator.(*Context).ExecutePackage(0xc0006bcc60, 0xc000132d80, 0x17, 0x2ce7ae0, 0xc000597980, 0x0, 0x0)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/generator/execute.go:265 +0xbf7
k8s.io/gengo/generator.(*Context).ExecutePackages(0xc0006bcc60, 0xc000132d80, 0x17, 0xc00061a4e0, 0x1, 0x1, 0x0, 0xc000132f00)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/generator/execute.go:51 +0xc5
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc0004adae0, 0xc00065b810, 0x296a2c4, 0x6, 0x2a5f9d8, 0xc000132cc0, 0x1b)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/args/args.go:194 +0x2d7
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.deepcopyGen(0xc00043dd00, 0x3a, 0xc000149480, 0x2, 0x2, 0x18, 0xc00065b9b0)
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:94 +0x4d2
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen.func1(0xc00043dd00, 0x3a, 0xc00043dd00, 0x3a)
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:53 +0x50
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.generateWithHeaderFile(0xc0001494a0, 0x0, 0x0)
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/genutil.go:104 +0x178
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen(0xc00015ca00, 0x0)
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:54 +0x4a5
github.com/operator-framework/operator-sdk/cmd/operator-sdk/generate.k8sFunc(0xc00015ca00, 0x401fc80, 0x0, 0x0, 0x0, 0x0)
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/generate/k8s.go:56 +0x156
github.com/spf13/cobra.(*Command).execute(0xc00015ca00, 0x401fc80, 0x0, 0x0, 0xc00015ca00, 0x401fc80)
	pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000463400, 0x2c9b2e0, 0xc000380e00, 0x0)
	pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/main.go:85 +0x50f
make: *** [deepcopy-gen] Error 255
```

**Comment by tomaszsek** [comment]
Hi @benlangfeld,

Could you provide your `operator-sdk` version?

Cheers

**Comment by benlangfeld** [comment]
@tomaszsek 

```
➭ operator-sdk version
operator-sdk version: v0.9.0, commit: 560208dc998de497bbf59fea1b63426aec430934
```

**Comment by tomaszsek** [comment]
@benlangfeld please use `0.8.1`
