### ISSUE TITLE
Slave PODs exception when connecting to master: Unknown client name: k8sagent-e2e-p7j97-fqf8j

### ISSUE THREAD

**Issue by tomsucho** [jenkinsci/kubernetes-operator#657]
**Describe the bug**
I installed operator via helm and things started fine, the seed job was executed also so tried runnign the test job:
"Kubernetes Plugin E2E Test", however it fails i.e. it spins up several pods, but all of them error out (detailed log down below)

java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Unknown client name: k8sagent-e2e-p7j97-fqf8j

Wonder if something is missing somewhere, or if it is some kind of a bug? 
Kindly please help.

**To Reproduce**
Just follow the steps with helm install for operator:
https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator/

and apply example CR for bringing up example jenkins master from:
https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/deploying-jenkins/

Kubernetes version:
```[ubuntu@ubuntu2004 Jenkins-Operator (⎈ |minikube:jenkins-operator)]$ minikube version
minikube version: v1.23.2
commit: 0a0ad764652082477c00d51d2475284b5d39ceed

[ubuntu@ubuntu2004 Jenkins-Operator (⎈ |minikube:default)]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
Jenkins Operator version:
```
NAME            	NAMESPACE       	REVISION	UPDATED                                 	STATUS  	CHART                 	APP VERSION
jenkins-operator	jenkins-operator	1       	2021-09-23 16:19:57.604813041 +0200 CEST	deployed	jenkins-operator-0.5.3	0.6.0 
```

Add error logs about the problem here (operator logs and Kubernetes events).

```
[ubuntu@ubuntu2004 Jenkins-Operator (⎈ |minikube:default)]$ kubectl get po
NAME                                     READY   STATUS    RESTARTS   AGE
jenkins-example                          1/1     Running   0          3m40s
k8sagent-e2e-p7j97-1wd6g                 2/2     Running   0          2s
k8sagent-e2e-p7j97-fqf8j                 1/2     Error     0          12s
seed-job-agent-example-8cd964544-gzk4x   1/1     Running   0          117s
```

```
[ubuntu@ubuntu2004 Jenkins-Operator (⎈ |minikube:default)]$ kubectl logs k8sagent-e2e-p7j97-fqf8j -c jnlp 
Sep 23, 2021 2:37:57 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: k8sagent-e2e-p7j97-fqf8j
Sep 23, 2021 2:37:57 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Sep 23, 2021 2:37:57 PM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 4.3
Sep 23, 2021 2:37:57 PM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using /home/jenkins/agent/remoting as a remoting work directory
Sep 23, 2021 2:37:57 PM org.jenkinsci.remoting.engine.WorkDirManager setupLogging
INFO: Both error and output logs will be printed to /home/jenkins/agent/remoting
Sep 23, 2021 2:37:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://jenkins-operator-http-example.default.svc.cluster.local:8080/]
Sep 23, 2021 2:37:57 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
Sep 23, 2021 2:37:57 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting TCP connection tunneling is enabled. Skipping the TCP Agent Listener Port availability check
Sep 23, 2021 2:37:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: jenkins-operator-slave-example.default.svc.cluster.local
  Agent port:    50000
  Identity:      94:f7:9c:e5:3f:c0:c2:42:2e:e9:03:57:0e:47:6a:8b
Sep 23, 2021 2:37:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Sep 23, 2021 2:37:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to jenkins-operator-slave-example.default.svc.cluster.local:50000
Sep 23, 2021 2:37:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP4-connect
Sep 23, 2021 2:37:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Remote identity confirmed: 94:f7:9c:e5:3f:c0:c2:42:2e:e9:03:57:0e:47:6a:8b
Sep 23, 2021 2:37:57 PM org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer onRecv
INFO: [JNLP4-connect connection to jenkins-operator-slave-example.default.svc.cluster.local/10.98.69.95:50000] Local headers refused by remote: Unknown client name: k8sagent-e2e-p7j97-fqf8j
Sep 23, 2021 2:37:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Unknown client name: k8sagent-e2e-p7j97-fqf8j
	at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223)
	at hudson.remoting.Engine.innerRun(Engine.java:743)
	at hudson.remoting.Engine.run(Engine.java:518)
```

On the master node I can see something like follows:
```
2021-09-23 14:51:55.190+0000 [id=368]	INFO	hudson.slaves.NodeProvisioner#lambda$update$6: k8sagent-e2e-9sgkr-05mn3 provisioning successfully completed. We have now 3 computer(s)
2021-09-23 14:51:55.200+0000 [id=369]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Created Pod: kubernetes default/k8sagent-e2e-9sgkr-05mn3
2021-09-23 14:51:55.203+0000 [id=369]	WARNING	o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: k8sagent-e2e-9sgkr-05mn3, template=PodTemplate{id='b76d2fb2-a0e9-4f19-bcbc-43c89bc303b7', name='k8sagent-e2e-9sgkr', namespace='default', label='k8sagent-e2e', containers=[ContainerTemplate{name='alpine', image='alpine:3.11', command='cat', ttyEnabled=true}], annotations=[PodAnnotation{key='buildUrl', value='http://jenkins-operator-http-example.default.svc.cluster.local:8080/job/k8s-e2e/3/'}, PodAnnotation{key='runUrl', value='job/k8s-e2e/3/'}]}
java.lang.NoSuchMethodError: io.fabric8.kubernetes.client.dsl.PodResource.watch(Ljava/lang/Object;)Ljava/lang/Object;
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:168)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-09-23 14:51:55.203+0000 [id=369]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent k8sagent-e2e-9sgkr-05mn3
2021-09-23 14:51:56.494+0000 [id=413]	INFO	h.TcpSlaveAgentListener$ConnectionHandler#run: Accepted JNLP4-connect connection #4 from /172.17.0.1:30022
2021-09-23 14:51:56.602+0000 [id=369]	INFO	o.j.r.p.i.ConnectionHeadersFilterLayer#onRecv: [JNLP4-connect connection from 172.17.0.1/172.17.0.1:30022] Refusing headers from remote: Unknown client name: k8sagent-e2e-9sgkr-05mn3
```

**What I tried already**
Setting this in http://master/script
jenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification=true
but it didn't seem to help for the issue

**Comment by Sig00rd** [comment]
Hello @tomsucho, thanks for reporting this.
I couldn't reproduce the problem you mentioned, so for now I'll explain what I did to get it running (while staying close to the installation methods you mentioned) and we'll see if you missed something.
First, I installed the Operator with Helm, providing values.yaml with:
1. `jenkins.enabled` set to false. That's because by default, installing the Operator with Helm deploys Jenkins as well, and deploying another Jenkins from manifest is known to make the whole installation faulty as the Operator can only handle one Jenkins instance.
2.`operator.image` set to `virtuslab/jenkins-operator:31c8368`. The thing here is that the last released version uses alpine Jenkins agent image, which was bugged, so it was replaced in the codebase, but not yet released. Nightly built Operator images have this fix, so I used the newest one. 
Then, I deployed Jenkins resource as per instructions in the docs, and both seed job and Kubernetes plugin e2e job ran without problems.

Please let me know if this explanation rings a bell for you. Omitting the two things I mentioned is a probable source of errors, but I'm not sure if you hadn't actually done those, and I have to admit I've not yet seen an error like the one you posted. For all I know, it might be a bug.

**Comment by Sig00rd** [comment]
Great news, thanks for letting me know!
