### ISSUE TITLE
Failed to initialise k8s secret provider

### ISSUE THREAD

**Issue by christophfritze** [jenkinsci/kubernetes-operator#697]
**Describe the bug**
I deployed Jenkins Operator successfully. To deploy the Jenkins master instance following [the manual](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/deploying-jenkins/) I get the following error in the logs

```2022-01-06 13:38:58.042+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @924ms to org.eclipse.jetty.util.log.JavaUtilLog
2022-01-06 13:38:58.240+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
2022-01-06 13:38:59.376+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2022-01-06 13:38:59.455+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.43.v20210629; built: 2021-06-30T11:07:22.254Z; git: 526006ecfa3af7f1a27ef3a288e2bef7ea9dd7e8; jvm 11.0.13+8
2022-01-06 13:38:59.972+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2022-01-06 13:39:00.067+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2022-01-06 13:39:00.067+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2022-01-06 13:39:00.068+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 660000ms
2022-01-06 13:39:01.055+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/lib/jenkins found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2022-01-06 13:39:01.371+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@216914{Jenkins v2.319.1,/,file:///var/lib/jenkins/war/,AVAILABLE}{/var/lib/jenkins/war}
2022-01-06 13:39:01.440+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@72cf2de5{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2022-01-06 13:39:01.441+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @4325ms
2022-01-06 13:39:01.442+0000 [id=23]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2022-01-06 13:39:01.863+0000 [id=30]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2022-01-06 13:39:02.860+0000 [id=29]	INFO	hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/lib/jenkins/plugins/command-launcher.jpi
2022-01-06 13:39:02.868+0000 [id=29]	INFO	hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/lib/jenkins/plugins/jdk-tool.jpi
2022-01-06 13:39:02.876+0000 [id=29]	INFO	hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/lib/jenkins/plugins/jaxb.jpi
2022-01-06 13:39:05.658+0000 [id=30]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/var/lib/jenkins/war/WEB-INF/lib/guice-4.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-01-06 13:39:13.643+0000 [id=30]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2022-01-06 13:39:13.656+0000 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
2022-01-06 13:39:15.846+0000 [id=30]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2022-01-06 13:39:16.130+0000 [id=31]	INFO	c.c.j.p.k.KubernetesCredentialProvider#startWatchingForSecrets: retrieving secrets with selector: jenkins.io/credentials-type, LabelSelector(matchExpressions=[], matchLabels=null, additionalProperties={})
2022-01-06 13:39:18.357+0000 [id=30]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
2022-01-06 13:39:18.755+0000 [id=29]	INFO	jenkins.InitReactorRunner$1#onAttained: System config adapted
2022-01-06 13:39:18.755+0000 [id=29]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2022-01-06 13:39:18.756+0000 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
2022-01-06 13:39:18.765+0000 [id=46]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Started Download metadata
2022-01-06 13:39:18.823+0000 [id=28]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /var/lib/jenkins/init.groovy.d/createOperatorUser.groovy
2022-01-06 13:39:18.831+0000 [id=46]	INFO	hudson.util.Retrier#start: Attempt #1 to do the action check updates server
2022-01-06 13:39:27.043+0000 [id=31]	SEVERE	c.c.j.p.k.KubernetesCredentialProvider#startWatchingForSecrets: Failed to initialise k8s secret provider, secrets from Kubernetes will not be available
java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
Caused: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:232)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:354)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:226)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:384)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:220)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:161)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientBuilderImpl$InteceptorAdapter.intercept(OkHttpClientBuilderImpl.java:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientBuilderImpl$InteceptorAdapter.intercept(OkHttpClientBuilderImpl.java:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientBuilderImpl$InteceptorAdapter.intercept(OkHttpClientBuilderImpl.java:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientBuilderImpl$InteceptorAdapter.intercept(OkHttpClientBuilderImpl.java:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl.send(OkHttpClientImpl.java:138)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:575)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:554)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:519)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:503)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:131)
Caused: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Secret]  with name: [null]  in namespace: [jenkins-operator]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:130)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:138)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:413)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:402)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:83)
	at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.KubernetesCredentialProvider.startWatchingForSecrets(KubernetesCredentialProvider.java:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:180)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-01-06 13:39:27.045+0000 [id=31]	INFO	c.c.j.p.k.KubernetesCredentialProvider#reconnectLater: Attempting to reconnect Kubernetes client in 5 mins
2022-01-06 13:39:27.047+0000 [id=31]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
2022-01-06 13:39:27.146+0000 [id=22]	INFO	hudson.WebAppMain$3#run: Jenkins is fully up and running
2022-01-06 13:39:40.462+0000 [id=46]	INFO	h.m.DownloadService$Downloadable#load: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller
2022-01-06 13:39:41.652+0000 [id=46]	INFO	h.m.DownloadService$Downloadable#load: Obtained the updated data file for hudson.tools.JDKInstaller
2022-01-06 13:39:41.653+0000 [id=46]	INFO	hudson.util.Retrier#start: Performed the action check updates server successfully at the attempt #1
2022-01-06 13:39:41.655+0000 [id=46]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Finished Download metadata. 22,889 ms
```

**To Reproduce**

Deploy Jenkins Operator using Helm Chart with the manual [here](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator/) and set flag `jenkins.enabled=false`.

Jenkins instance manifest:
```
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins-test
  namespace: jenkins-operator
spec:
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    disableCSRFProtection: false
    basePlugins:
    - name: kubernetes
      version: "1.31.2"
    - name: workflow-job
      version: "1145.v7f2433caa07f"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.10.0"
    - name: job-dsl
      version: "1.78.1"
    - name: configuration-as-code
      version: "1.55"
    - name: kubernetes-credentials-provider
      version: "0.20"
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 800
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 800
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
        env:
        - name: http_proxy
          value: http://XXX:3128
        - name: https_proxy
          value: http://XXX:3128
        - name: no_proxy
          value: 127.0.0.1,localhost,.local,.internal
        - name: HTTP_PROXY
          value: http://XXX:3128
        - name: HTTPS_PROXY
          value: http://XXX:3128
        - name: NO_PROXY
          value: 127.0.0.1,localhost,.local,.internal
  seedJobs:
    - id: jenkins-operator
      targets: "cicd/jobs/*.jenkins"
      description: "Jenkins Operator repository"
      repositoryBranch: master
      repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
```

**Additional information**

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:09:28Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
Jenkins Operator version:  0.6.0 (latest Helm chart)

Secrets:
```
kubectl get secrets -n jenkins-operator
NAME                                        TYPE                                  DATA   AGE
default-token-ck8sr                         kubernetes.io/service-account-token   3      161m
jenkins-operator-credentials-jenkins-test   Opaque                                4      159m
jenkins-operator-jenkins-test-token-s9gtc   kubernetes.io/service-account-token   3      159m
jenkins-operator-token-fgh22                kubernetes.io/service-account-token   3      161m
```
Pods:
```
kubectl get pods -n jenkins-operator
NAME                                           READY   STATUS    RESTARTS   AGE
jenkins-jenkins-test                           1/1     Running   0          23m
jenkins-operator-b6664d86b-xvjx9               1/1     Running   0          161m
seed-job-agent-jenkins-test-69f8c5bc59-s2zcd   1/1     Running   0          9m29s
```

Thanks!

**Comment by thecooldrop** [comment]
You did not set the labelSelector JVM system property while starting your Jenkins instance, which is required in order for plugin to work properly. Please consult the [plugin documentation](https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/) and the source code of the [class where the error occurs](https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/).

@Sig00rd Please close this issue to keep the backlog clean

**Comment by christophfritze** [comment]
@thecooldrop Thanks for the response, but it was not the cause of the problem.
We discovered that the env variables are the problem.
Removing the variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY resolved it!

**Comment by christophfritze** [comment]
Setting the labelSelector is **not** required for the use of the plugin.
