### ISSUE TITLE
install jenkins-operator v0.7x problem

### ISSUE THREAD

**Issue by zxcasdqw** [jenkinsci/kubernetes-operator#701]
**When I installed jenkins-operator 0.7.0 version, I encountered the following problem. Below is the full log.**

$ minikube version
minikube version: v1.8.1
commit: cbda04cf6bbe65e987ae52bb393c10099ab62014
$ minikube start --wait=false
* minikube v1.8.1 on Ubuntu 18.04
* Using the none driver based on user configuration
* Running on localhost (CPUs=2, Memory=2460MB, Disk=145651MB) ...
* OS release is Ubuntu 18.04.4 LTS
* Preparing Kubernetes v1.17.3 on Docker 19.03.6 ...
  - kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
* Launching Kubernetes ... 
* Enabling addons: default-storageclass, storage-provisioner
* Configuring local host environment ...
* Done! kubectl is now configured to use "minikube"
$ kubectl cluster-info
Kubernetes master is running at https://172.17.0.101:8443
KubeDNS is running at https://172.17.0.101:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
$ kubectl get nodes
NAME       STATUS     ROLES    AGE   VERSION
minikube   NotReady   master   17s   v1.17.3
$ kubectl apply -f https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/config/crd/bases/jenkins.io_jenkins.yaml
customresourcedefinition.apiextensions.k8s.io/jenkins.jenkins.io created
$ kubectl apply -f https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/all-in-one-v1alpha2.yaml
serviceaccount/jenkins-operator created
role.rbac.authorization.k8s.io/leader-election-role created
rolebinding.rbac.authorization.k8s.io/leader-election-rolebinding created
role.rbac.authorization.k8s.io/jenkins-operator created
rolebinding.rbac.authorization.k8s.io/manager-rolebinding created
deployment.apps/jenkins-operator created
$ kubectl get pods -w
NAME                                READY   STATUS    RESTARTS   AGE
jenkins-operator-59657578dd-stdwn   0/1     Running   0          12s
jenkins-operator-59657578dd-stdwn   1/1     Running   0          16s
^C$ vi jenkins.yaml
$ kubectl create -f jenkins.yaml 
jenkins.jenkins.io/example created
$ kubectl get pods -w
NAME                                READY   STATUS              RESTARTS   AGE
jenkins-example                     0/1     ContainerCreating   0          13s
jenkins-operator-59657578dd-stdwn   1/1     Running             0          89s
jenkins-example                     0/1     Running             0          20s
^C$ ^C
$ kubectl logs -f --tail=200 jenkins-example 
Downloading plugin: workflow-durable-task-step from https://updates.jenkins.io/dynamic-2.319//latest/workflow-durable-task-step.hpi
Downloading plugin: git-client from https://updates.jenkins.io/dynamic-2.319//latest/git-client.hpi
Skipping optional dependency matrix-project
Downloading plugin: mailer from https://updates.jenkins.io/dynamic-2.319//latest/mailer.hpi
Skipping optional dependency parameterized-trigger
Downloading plugin: workflow-multibranch from https://updates.jenkins.io/dynamic-2.319//latest/workflow-multibranch.hpi
Downloading plugin: durable-task from https://updates.jenkins.io/dynamic-2.319//latest/durable-task.hpi
Skipping optional dependency promoted-builds
 > job-dsl depends on config-file-provider:2.15.4;resolution:=optional,configuration-as-code:1.15;resolution:=optional,managed-scripts:1.3;resolution:=optional,cloudbees-folder:5.14,structs:1.19,script-security:1.54,vsphere-cloud:1.1.11;resolution:=optional
Skipping optional dependency config-file-provider
Downloading plugin: jackson2-api from https://updates.jenkins.io/dynamic-2.319//latest/jackson2-api.hpi
Skipping optional dependency configuration-as-code
Skipping optional dependency managed-scripts
Downloading plugin: scm-api from https://updates.jenkins.io/dynamic-2.319//latest/scm-api.hpi
Downloading plugin: ssh-credentials from https://updates.jenkins.io/dynamic-2.319//latest/ssh-credentials.hpi
Downloading plugin: metrics from https://updates.jenkins.io/dynamic-2.319//latest/metrics.hpi
Downloading plugin: script-security from https://updates.jenkins.io/dynamic-2.319//latest/script-security.hpi
Downloading plugin: plain-credentials from https://updates.jenkins.io/dynamic-2.319//latest/plain-credentials.hpi
 > lockable-resources depends on caffeine-api:2.9.1-23.v51c4e2c879c8,workflow-support:3.8,mailer:1.34,matrix-project:1.18,script-security:1.78,structs:1.23
Skipping optional dependency token-macro
Downloading plugin: structs from https://updates.jenkins.io/dynamic-2.319//latest/structs.hpi
Skipping optional dependency vsphere-cloud
 > credentials depends on configuration-as-code:1.55;resolution:=optional,structs:308.v852b473a2b8c
Skipping optional dependency configuration-as-code
Downloading plugin: pipeline-build-step from https://updates.jenkins.io/dynamic-2.319//latest/pipeline-build-step.hpi
 > pipeline-stage-view depends on pipeline-rest-api:2.20,workflow-api:2.46,workflow-job:2.41,handlebars:1.1.1,momentjs:1.1
Skipping optional dependency pipeline-model-extensions
Downloading plugin: kubernetes-credentials from https://updates.jenkins.io/dynamic-2.319//latest/kubernetes-credentials.hpi
Downloading plugin: pipeline-input-step from https://updates.jenkins.io/dynamic-2.319//latest/pipeline-input-step.hpi
Downloading plugin: pipeline-rest-api from https://updates.jenkins.io/dynamic-2.319//latest/pipeline-rest-api.hpi
Downloading plugin: pipeline-milestone-step from https://updates.jenkins.io/dynamic-2.319//latest/pipeline-milestone-step.hpi
 > workflow-api depends on workflow-step-api:2.23,scm-api:2.6.4
Downloading plugin: matrix-project from https://updates.jenkins.io/dynamic-2.319//latest/matrix-project.hpi
Downloading plugin: pipeline-stage-step from https://updates.jenkins.io/dynamic-2.319//latest/pipeline-stage-step.hpi
 > workflow-support depends on workflow-api:1108.v57edf648f5d4,workflow-step-api:622.vb_8e7c15b_c95a_,scm-api:2.6.5,script-security:1118.vba21ca2e3286
 > cloudbees-folder depends on credentials:2.5;resolution:=optional
 > workflow-basic-steps depends on workflow-api:2.46,workflow-durable-task-step:2.39,workflow-step-api:2.24,apache-httpcomponents-client-4-api:4.5.13-1.0,mailer:1.34,structs:1.23
 > workflow-step-api depends on structs:1.23
Skipping optional dependency credentials
Downloading plugin: pipeline-model-definition from https://updates.jenkins.io/dynamic-2.319//latest/pipeline-model-definition.hpi
 > workflow-scm-step depends on workflow-step-api:2.23
 > workflow-cps depends on workflow-api:2.46,workflow-scm-step:2.13,workflow-step-api:2.23,workflow-support:3.8,scm-api:2.6.4,script-security:1.77,structs:1.23,support-core:2.43;resolution:=optional,ace-editor:1.1
 > credentials-binding depends on workflow-step-api:2.23,credentials:2.5,plain-credentials:1.7,ssh-credentials:1.18.1,structs:1.23
Downloading plugin: handlebars from https://updates.jenkins.io/dynamic-2.319//latest/handlebars.hpi
Downloading plugin: momentjs from https://updates.jenkins.io/dynamic-2.319//latest/momentjs.hpi
 > workflow-durable-task-step depends on workflow-api:1108.v57edf648f5d4,workflow-step-api:622.vb_8e7c15b_c95a_,workflow-support:804.vba10a18a1476,durable-task:493.v195aefbb0ff2,scm-api:2.6.5,script-security:1118.vba21ca2e3286,structs:308.v852b473a2b8c
 > authentication-tokens depends on credentials:1.22
 > workflow-multibranch depends on workflow-api:2.47,workflow-cps:2.94,workflow-job:2.41,workflow-scm-step:2.13,workflow-step-api:2.24,workflow-support:3.8,branch-api:2.7.0,cloudbees-folder:6.16,scm-api:2.6.5,script-security:1.78
Downloading plugin: apache-httpcomponents-client-4-api from https://updates.jenkins.io/dynamic-2.319//latest/apache-httpcomponents-client-4-api.hpi
 > mailer depends on javax-mail-api:1.6.2-2,display-url-api:2.3.5
 > workflow-cps-global-lib depends on workflow-api:2.47,workflow-cps:2.94,workflow-step-api:2.24,workflow-support:3.8,cloudbees-folder:6.16,credentials:2.6.1,git-server:1.10,scm-api:2.6.5,script-security:1.78
 > scm-api depends on structs:308.v852b473a2b8c
 > metrics depends on workflow-durable-task-step:2.35;resolution:=optional,jackson2-api:2.10.2,variant:1.3
Skipping optional dependency workflow-durable-task-step
 > plain-credentials depends on credentials:2.2.0
Downloading plugin: javax-mail-api from https://updates.jenkins.io/dynamic-2.319//latest/javax-mail-api.hpi
Skipping optional dependency support-core
Downloading plugin: display-url-api from https://updates.jenkins.io/dynamic-2.319//latest/display-url-api.hpi
 > script-security depends on caffeine-api:2.9.2-29.v717aac953ff3
Downloading plugin: ace-editor from https://updates.jenkins.io/dynamic-2.319//latest/ace-editor.hpi
 > ssh-credentials depends on credentials:2.5,trilead-api:1.0.13
 > pipeline-build-step depends on workflow-api:2.46,workflow-step-api:2.23,workflow-support:3.8,script-security:1.77,structs:1.23
 > jackson2-api depends on jersey2-api:2.35-1;resolution:=optional,snakeyaml-api:1.29.1
Skipping optional dependency jersey2-api
 > pipeline-milestone-step depends on workflow-api:2.11,workflow-step-api:2.9
 > git-client depends on configuration-as-code:1.54;resolution:=optional,apache-httpcomponents-client-4-api:4.5.13-1.0,credentials:2.6.1,jsch:0.1.55.2,script-security:1.78,ssh-credentials:1.19,structs:1.23,trilead-api:1.0.13
 > kubernetes-credentials depends on apache-httpcomponents-client-4-api:4.5.5-3.0,authentication-tokens:1.3,credentials:2.3.5,docker-commons:1.15;resolution:=optional,google-oauth-plugin:0.8;resolution:=optional,jackson2-api:2.11.0,kubernetes-client-api:4.9.2-2,plain-credentials:1.6;resolution:=optional
Skipping optional dependency configuration-as-code
Downloading plugin: branch-api from https://updates.jenkins.io/dynamic-2.319//latest/branch-api.hpi
 > pipeline-input-step depends on workflow-api:2.46,workflow-step-api:2.23,workflow-support:3.8,credentials:2.5,structs:1.23
Downloading plugin: trilead-api from https://updates.jenkins.io/dynamic-2.319//latest/trilead-api.hpi
Downloading plugin: git-server from https://updates.jenkins.io/dynamic-2.319//latest/git-server.hpi
 > pipeline-rest-api depends on workflow-api:2.46,workflow-job:2.41,workflow-step-api:2.24,workflow-support:3.8,jackson2-api:2.12.4,pipeline-graph-analysis:1.4,pipeline-input-step:2.12,pipeline-stage-step:2.5
 > pipeline-stage-step depends on workflow-api:2.46,workflow-step-api:2.23
Downloading plugin: jsch from https://updates.jenkins.io/dynamic-2.319//latest/jsch.hpi
Skipping optional dependency docker-commons
Skipping optional dependency google-oauth-plugin
 > matrix-project depends on junit:1.47,script-security:1.75
Skipping optional dependency plain-credentials
Downloading plugin: junit from https://updates.jenkins.io/dynamic-2.319//latest/junit.hpi
Downloading plugin: pipeline-graph-analysis from https://updates.jenkins.io/dynamic-2.319//latest/pipeline-graph-analysis.hpi
 > pipeline-model-definition depends on workflow-api:2.46,workflow-basic-steps:2.20,workflow-cps-global-lib:2.19,workflow-cps:2.93,workflow-durable-task-step:2.35,workflow-multibranch:2.24,workflow-scm-step:2.13,workflow-support:3.8,credentials-binding:1.27,credentials:2.5,git-client:3.6.0,mailer:1.34,pipeline-input-step:2.12,pipeline-stage-step:2.5,scm-api:2.6.4,structs:1.23,pipeline-model-api:1.9.3,pipeline-model-extensions:1.9.3,pipeline-stage-tags-metadata:1.9.3
 > javax-mail-api depends on javax-activation-api:1.2.0-2
Downloading plugin: javax-activation-api from https://updates.jenkins.io/dynamic-2.319//latest/javax-activation-api.hpi
 > branch-api depends on cloudbees-folder:6.16,scm-api:2.6.5
 > kubernetes-client-api depends on snakeyaml-api:1.29.1,bouncycastle-api:2.25,jackson2-api:2.12.4
Downloading plugin: pipeline-model-api from https://updates.jenkins.io/dynamic-2.319//latest/pipeline-model-api.hpi
Downloading plugin: bouncycastle-api from https://updates.jenkins.io/dynamic-2.319//latest/bouncycastle-api.hpi
Downloading plugin: pipeline-model-extensions from https://updates.jenkins.io/dynamic-2.319//latest/pipeline-model-extensions.hpi
Downloading plugin: pipeline-stage-tags-metadata from https://updates.jenkins.io/dynamic-2.319//latest/pipeline-stage-tags-metadata.hpi
 > git-server depends on sshd:3.0.4,git-client:2.7.6
Downloading plugin: sshd from https://updates.jenkins.io/dynamic-2.319//latest/sshd.hpi
 > jsch depends on ssh-credentials:1.14,trilead-api:1.0.5
 > junit depends on bootstrap4-api:4.6.0-3,checks-api:1.7.2,echarts-api:5.0.2-1,plugin-util-api:2.4.0,workflow-api:2.46,workflow-step-api:2.24,display-url-api:2.3.5,jackson2-api:2.12.4,script-security:1.78
 > pipeline-graph-analysis depends on workflow-api:1105.v3de5e2efac97,workflow-cps:2.94,workflow-job:1145.v7f2433caa07f,workflow-step-api:615.vb09dac339255,workflow-support:3.8,pipeline-input-step:427.va6441fa17010,pipeline-stage-step:2.5
Downloading plugin: bootstrap4-api from https://updates.jenkins.io/dynamic-2.319//latest/bootstrap4-api.hpi
Downloading plugin: checks-api from https://updates.jenkins.io/dynamic-2.319//latest/checks-api.hpi
Downloading plugin: echarts-api from https://updates.jenkins.io/dynamic-2.319//latest/echarts-api.hpi
Downloading plugin: plugin-util-api from https://updates.jenkins.io/dynamic-2.319//latest/plugin-util-api.hpi
 > pipeline-model-extensions depends on workflow-cps:2.93,workflow-job:2.41,credentials-binding:1.27,credentials:2.5,pipeline-stage-step:2.5,pipeline-model-api:1.9.3
 > pipeline-stage-tags-metadata depends on workflow-api:2.46
 > pipeline-model-api depends on workflow-step-api:2.24,jackson2-api:2.12.4,structs:1.23
 > checks-api depends on plugin-util-api:2.4.0,workflow-step-api:2.23,workflow-support:3.8,display-url-api:2.3.5
 > bootstrap4-api depends on font-awesome-api:5.15.2-2,jquery3-api:3.5.1-3,popper-api:1.16.1-2
Downloading plugin: font-awesome-api from https://updates.jenkins.io/dynamic-2.319//latest/font-awesome-api.hpi
Downloading plugin: jquery3-api from https://updates.jenkins.io/dynamic-2.319//latest/jquery3-api.hpi
Downloading plugin: popper-api from https://updates.jenkins.io/dynamic-2.319//latest/popper-api.hpi
 > echarts-api depends on bootstrap5-api:5.1.3-4,font-awesome-api:5.15.4-5,jquery3-api:3.6.0-2,plugin-util-api:2.8.0,jackson2-api:2.13.0-230.v59243c64b0a5
Downloading plugin: bootstrap5-api from https://updates.jenkins.io/dynamic-2.319//latest/bootstrap5-api.hpi
 > font-awesome-api depends on plugin-util-api:2.8.0
 > bootstrap5-api depends on font-awesome-api:5.15.4-5,popper2-api:2.11.0-1
Downloading plugin: popper2-api from https://updates.jenkins.io/dynamic-2.319//latest/popper2-api.hpi

WAR bundled plugins:

Installed plugins:
ace-editor:1.1
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-4
bouncycastle-api:2.25
branch-api:2.7.0
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-folder:6.17
configuration-as-code:1.55
credentials-binding:1.27.1
credentials:1074.v60e6c29b_b_44b_
display-url-api:2.3.5
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-2
font-awesome-api:5.15.4-5
git-client:3.11.0
git-server:1.10
git:4.10.0
handlebars:3.0.8
jackson2-api:2.13.1-246.va8a9f3eaf46a
javax-activation-api:1.2.0-2
javax-mail-api:1.6.2-5
job-dsl:1.78.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
kubernetes-client-api:5.11.2-182.v0f1cf4c5904e
kubernetes-credentials-provider:0.20
kubernetes-credentials:0.9.0
kubernetes:1.30.11
lockable-resources:2.13
mailer:408.vd726a_1130320
matrix-project:1.20
metrics:4.0.2.8.1
momentjs:1.1.1
pipeline-build-step:2.15
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:427.va6441fa17010
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.20
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.20
plain-credentials:1.7
plugin-util-api:2.12.0
popper-api:1.16.1-2
popper2-api:2.11.2-1
scm-api:595.vd5a_df5eb_0e39
script-security:1131.v8b_b_5eda_c328e
snakeyaml-api:1.29.1
ssh-credentials:1.19
sshd:3.1.0
structs:308.v852b473a2b8c
trilead-api:1.0.13
variant:1.4
workflow-aggregator:2.6
workflow-api:1122.v7a_916f363c86
workflow-basic-steps:2.24
workflow-cps-global-lib:552.vd9cc05b8a2e1
workflow-cps:2648.va9433432b33c
workflow-durable-task-step:1121.va_65b_d2701486
workflow-job:2.42
workflow-multibranch:706.vd43c65dec013
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:813.vb_d7c3d2984a_0
Cleaning up locks
+ echo 'Installing plugins required by Operator - end'
Installing plugins required by Operator - end
+ echo 'Installing plugins required by user - begin'
Installing plugins required by user - begin
+ cat
+ [[ -z '' ]]
+ install-plugins.sh
WARN: install-plugins.sh is deprecated, please switch to jenkins-plugin-cli
Creating initial locks...
Analyzing war /usr/share/jenkins/jenkins.war...
Registering preinstalled plugins...
Using version-specific update center: https://updates.jenkins.io/dynamic-2.319/...
Downloading plugins...

WAR bundled plugins:

Installed plugins:
ace-editor:1.1
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-4
bouncycastle-api:2.25
branch-api:2.7.0
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-folder:6.17
configuration-as-code:1.55
credentials-binding:1.27.1
credentials:1074.v60e6c29b_b_44b_
display-url-api:2.3.5
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-2
font-awesome-api:5.15.4-5
git-client:3.11.0
git-server:1.10
git:4.10.0
handlebars:3.0.8
jackson2-api:2.13.1-246.va8a9f3eaf46a
javax-activation-api:1.2.0-2
javax-mail-api:1.6.2-5
job-dsl:1.78.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
kubernetes-client-api:5.11.2-182.v0f1cf4c5904e
kubernetes-credentials-provider:0.20
kubernetes-credentials:0.9.0
kubernetes:1.30.11
lockable-resources:2.13
mailer:408.vd726a_1130320
matrix-project:1.20
metrics:4.0.2.8.1
momentjs:1.1.1
pipeline-build-step:2.15
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:427.va6441fa17010
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.20
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.20
plain-credentials:1.7
plugin-util-api:2.12.0
popper-api:1.16.1-2
popper2-api:2.11.2-1
scm-api:595.vd5a_df5eb_0e39
script-security:1131.v8b_b_5eda_c328e
snakeyaml-api:1.29.1
ssh-credentials:1.19
sshd:3.1.0
structs:308.v852b473a2b8c
trilead-api:1.0.13
variant:1.4
workflow-aggregator:2.6
workflow-api:1122.v7a_916f363c86
workflow-basic-steps:2.24
workflow-cps-global-lib:552.vd9cc05b8a2e1
workflow-cps:2648.va9433432b33c
workflow-durable-task-step:1121.va_65b_d2701486
workflow-job:2.42
workflow-multibranch:706.vd43c65dec013
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:813.vb_d7c3d2984a_0
Cleaning up locks
Installing plugins required by user - end
+ echo 'Installing plugins required by user - end'
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2022-01-19 03:09:28.403+0000 [id=1]     INFO    org.eclipse.jetty.util.log.Log#initialized: Logging initialized @1899ms to org.eclipse.jetty.util.log.JavaUtilLog
2022-01-19 03:09:28.656+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
2022-01-19 03:09:31.381+0000 [id=1]     WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2022-01-19 03:09:31.674+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-9.4.43.v20210629; built: 2021-06-30T11:07:22.254Z; git: 526006ecfa3af7f1a27ef3a288e2bef7ea9dd7e8; jvm 11.0.13+8
2022-01-19 03:09:32.806+0000 [id=1]     INFO    o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2022-01-19 03:09:32.899+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2022-01-19 03:09:32.899+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2022-01-19 03:09:32.908+0000 [id=1]     INFO    o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 600000ms
2022-01-19 03:09:34.491+0000 [id=1]     INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/lib/jenkins found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2022-01-19 03:09:35.227+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started w.@216914{Jenkins v2.319.1,/,file:///var/lib/jenkins/war/,AVAILABLE}{/var/lib/jenkins/war}
2022-01-19 03:09:35.481+0000 [id=1]     INFO    o.e.j.server.AbstractConnector#doStart: Started ServerConnector@72cf2de5{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2022-01-19 03:09:35.483+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: Started @8982ms
2022-01-19 03:09:35.561+0000 [id=23]    INFO    winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2022-01-19 03:09:36.485+0000 [id=30]    INFO    jenkins.InitReactorRunner$1#onAttained: Started initialization
2022-01-19 03:09:37.261+0000 [id=30]    INFO    hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/lib/jenkins/plugins/command-launcher.jpi
2022-01-19 03:09:37.307+0000 [id=30]    INFO    hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/lib/jenkins/plugins/jdk-tool.jpi
2022-01-19 03:09:37.451+0000 [id=30]    INFO    hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/lib/jenkins/plugins/jaxb.jpi
2022-01-19 03:09:47.444+0000 [id=30]    INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2022-01-19 03:09:49.079+0000 [id=29]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline Graph Analysis Plugin v188.v3a01e7973f2c (pipeline-graph-analysis)
java.io.IOException: Failed to load: Pipeline Graph Analysis Plugin (188.v3a01e7973f2c)
 - Update required: Pipeline: Job (2.42) to be updated to 1145.v7f2433caa07f or higher
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2022-01-19 03:09:49.080+0000 [id=29]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: REST API Plugin v2.20 (pipeline-rest-api)
java.io.IOException: Failed to load: Pipeline: REST API Plugin (2.20)
 - Failed to load: Pipeline Graph Analysis Plugin (188.v3a01e7973f2c)
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2022-01-19 03:09:49.082+0000 [id=29]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Stage View Plugin v2.20 (pipeline-stage-view)
java.io.IOException: Failed to load: Pipeline: Stage View Plugin (2.20)
 - Failed to load: Pipeline: REST API Plugin (2.20)
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2022-01-19 03:09:49.612+0000 [id=30]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline v2.6 (workflow-aggregator)
java.io.IOException: Failed to load: Pipeline (2.6)
 - Failed to load: Pipeline: Stage View Plugin (2.20)
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/var/lib/jenkins/war/WEB-INF/lib/guice-4.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-01-19 03:10:46.797+0000 [id=28]    INFO    jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2022-01-19 03:10:47.084+0000 [id=28]    INFO    jenkins.InitReactorRunner$1#onAttained: Started all plugins
2022-01-19 03:10:56.952+0000 [id=29]    INFO    c.c.j.p.k.KubernetesCredentialProvider#startWatchingForSecrets: retrieving secrets with selector: jenkins.io/credentials-type, LabelSelector(matchExpressions=[], matchLabels=null, additionalProperties={})
2022-01-19 03:10:58.589+0000 [id=30]    INFO    jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2022-01-19 03:11:02.671+0000 [id=28]    INFO    jenkins.InitReactorRunner$1#onAttained: System config loaded
2022-01-19 03:11:04.500+0000 [id=30]    INFO    jenkins.InitReactorRunner$1#onAttained: System config adapted
2022-01-19 03:11:04.503+0000 [id=30]    INFO    jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2022-01-19 03:11:04.520+0000 [id=31]    INFO    jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
2022-01-19 03:11:04.600+0000 [id=55]    INFO    hudson.model.AsyncPeriodicWork#lambda$doRun$1: Started Download metadata
2022-01-19 03:11:04.953+0000 [id=28]    INFO    j.util.groovy.GroovyHookScript#execute: Executing /var/lib/jenkins/init.groovy.d/createOperatorUser.groovy
2022-01-19 03:11:05.137+0000 [id=55]    INFO    hudson.util.Retrier#start: Attempt #1 to do the action check updates server
2022-01-19 03:11:18.276+0000 [id=30]    INFO    jenkins.InitReactorRunner$1#onAttained: Completed initialization
2022-01-19 03:11:20.207+0000 [id=22]    INFO    hudson.WebAppMain$3#run: Jenkins is fully up and running
2022-01-19 03:11:34.732+0000 [id=75]    WARNING j.m.api.Metrics$HealthChecker#execute: Some health checks are reporting as unhealthy: [plugins : There are 4 failed plugins: pipeline-graph-analysis; pipeline-rest-api; pipeline-stage-view; workflow-aggregator]

**Comment by christophfritze** [comment]
The error message pretty much says it:
`Update required: Pipeline: Job (2.42) to be updated to 1145.v7f2433caa07f or higher`

I encountered the same problem using the defaults.

For example you could use the versions listed here:
```
basePlugins:
    - name: kubernetes
      version: "1.31.2"
    - name: workflow-job
      version: "1145.v7f2433caa07f"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.10.0"
    - name: job-dsl
      version: "1.78.1"
    - name: configuration-as-code
      version: "1.55"
    - name: kubernetes-credentials-provider
      version: "0.20"
```

**Comment by zxcasdqw** [comment]
thanks @christophfritze @MKajzik
