### ISSUE TITLE
Jenkins Operator pod crash after setting readinessProbe

### ISSUE THREAD

**Issue by tomvopat** [jenkinsci/kubernetes-operator#734]
**Describe the bug**
After updating jenkins.readinessProbe value, the jenkins-operator pod is constantly crashing.

**To Reproduce**
Add following to the values.yaml file

```yaml
jenkins:
  readinessProbe:
    httpGet: null
    tcpSocket:
      port: 8080
    initialDelaySeconds: 100
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 20
    timeoutSeconds: 8

```

**Additional information**

Kubernetes version: v1.23.3
Jenkins Operator version: v0.7.0

Add error logs about the problem here (operator logs and Kubernetes events).
```txt
2022-04-01T14:04:51.791Z	INFO	cmd	Version: v0.7.0
2022-04-01T14:04:51.791Z	INFO	cmd	Git commit: 76078d5f
2022-04-01T14:04:51.791Z	INFO	cmd	Go Version: go1.15.6
2022-04-01T14:04:51.791Z	INFO	cmd	Go OS/Arch: linux/amd64
2022-04-01T14:04:51.791Z	INFO	cmd	Watch namespace: default
2022-04-01T14:04:52.354Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": "0.0.0.0:8383"}
2022-04-01T14:04:52.365Z	INFO	cmd	starting manager
I0401 14:04:52.365732       1 leaderelection.go:243] attempting to acquire leader lease default/c674355f.jenkins.io...
2022-04-01T14:04:52.365Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
I0401 14:05:09.781344       1 leaderelection.go:253] successfully acquired lease default/c674355f.jenkins.io
2022-04-01T14:05:09.781Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"ConfigMap","namespace":"default","name":"c674355f.jenkins.io","uid":"558081be-b057-4061-a875-6c07605ae846","apiVersion":"v1","resourceVersion":"24308"}, "reason": "LeaderElection", "message": "operator-jenkins-operator-86cfc77989-4txhq_6fba009b-392a-4645-b49a-bb8fef28d629 became leader"}
2022-04-01T14:05:09.781Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"Lease","namespace":"default","name":"c674355f.jenkins.io","uid":"aa84887c-29a0-47e6-a7ed-db10c8d01e87","apiVersion":"coordination.k8s.io/v1","resourceVersion":"24310"}, "reason": "LeaderElection", "message": "operator-jenkins-operator-86cfc77989-4txhq_6fba009b-392a-4645-b49a-bb8fef28d629 became leader"}
2022-04-01T14:05:09.781Z	INFO	controller-runtime.manager.controller.jenkins	Starting EventSource	{"reconciler group": "jenkins.io", "reconciler kind": "Jenkins", "source": "kind source: jenkins.io/v1alpha2, Kind=Jenkins"}
2022-04-01T14:05:09.882Z	INFO	controller-runtime.manager.controller.jenkins	Starting EventSource	{"reconciler group": "jenkins.io", "reconciler kind": "Jenkins", "source": "kind source: /, Kind="}
2022-04-01T14:05:09.982Z	INFO	controller-runtime.manager.controller.jenkins	Starting EventSource	{"reconciler group": "jenkins.io", "reconciler kind": "Jenkins", "source": "kind source: /, Kind="}
2022-04-01T14:05:10.083Z	INFO	controller-runtime.manager.controller.jenkins	Starting EventSource	{"reconciler group": "jenkins.io", "reconciler kind": "Jenkins", "source": "kind source: /, Kind="}
2022-04-01T14:05:10.184Z	INFO	controller-runtime.manager.controller.jenkins	Starting EventSource	{"reconciler group": "jenkins.io", "reconciler kind": "Jenkins", "source": "kind source: core/v1, Kind=Secret"}
2022-04-01T14:05:10.184Z	INFO	controller-runtime.manager.controller.jenkins	Starting EventSource	{"reconciler group": "jenkins.io", "reconciler kind": "Jenkins", "source": "kind source: core/v1, Kind=ConfigMap"}
2022-04-01T14:05:10.184Z	INFO	controller-runtime.manager.controller.jenkins	Starting EventSource	{"reconciler group": "jenkins.io", "reconciler kind": "Jenkins", "source": "kind source: jenkins.io/v1alpha2, Kind=Jenkins"}
2022-04-01T14:05:10.184Z	INFO	controller-runtime.manager.controller.jenkins	Starting Controller	{"reconciler group": "jenkins.io", "reconciler kind": "Jenkins"}
2022-04-01T14:05:10.184Z	INFO	controller-runtime.manager.controller.jenkins	Starting workers	{"reconciler group": "jenkins.io", "reconciler kind": "Jenkins", "worker count": 1}
2022-04-01T14:05:10.184Z	INFO	controller-jenkins	*v1alpha2.Jenkins/jenkins was created	{"cr": "jenkins"}
2022-04-01T14:05:10.184Z	DEBUG	controller-jenkins	Reconciling Jenkins	{"cr": "jenkins"}
2022-04-01T14:05:10.285Z	DEBUG	controller-jenkins	Operator credentials secret is present	{"cr": "jenkins"}
2022-04-01T14:05:10.315Z	DEBUG	controller-jenkins	Scripts config map is present	{"cr": "jenkins"}
2022-04-01T14:05:10.352Z	DEBUG	controller-jenkins	Init configuration config map is present	{"cr": "jenkins"}
2022-04-01T14:05:10.443Z	DEBUG	controller-jenkins	Base configuration config map is present	{"cr": "jenkins"}
2022-04-01T14:05:10.443Z	DEBUG	controller-jenkins	GroovyScripts Secret and ConfigMap added watched labels	{"cr": "jenkins"}
2022-04-01T14:05:10.443Z	DEBUG	controller-jenkins	ConfigurationAsCode Secret and ConfigMap added watched labels	{"cr": "jenkins"}
2022-04-01T14:05:10.544Z	DEBUG	controller-jenkins	createServiceAccount with annotations map[]	{"cr": "jenkins"}
2022-04-01T14:05:10.676Z	DEBUG	controller-jenkins	Service account, role and role binding are present	{"cr": "jenkins"}
2022-04-01T14:05:10.776Z	DEBUG	controller-jenkins	Extra role bindings are present	{"cr": "jenkins"}
2022-04-01T14:05:10.879Z	DEBUG	controller-jenkins	Jenkins HTTP Service is present	{"cr": "jenkins"}
2022-04-01T14:05:10.881Z	DEBUG	controller-jenkins	Jenkins slave Service is present	{"cr": "jenkins"}
2022-04-01T14:05:10.881Z	DEBUG	controller-jenkins	Kubernetes resources are present	{"cr": "jenkins"}
E0401 14:05:10.881285       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 347 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x17c4aa0, 0x260c200)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x89
panic(0x17c4aa0, 0x260c200)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/jenkinsci/kubernetes-operator/pkg/configuration/base/resources.setLivenessAndReadinessPath(0xc00062e480)
	/workspace/pkg/configuration/base/resources/pod.go:267 +0x5c
github.com/jenkinsci/kubernetes-operator/pkg/configuration/base/resources.NewJenkinsMasterContainer(0xc00062e480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/pkg/configuration/base/resources/pod.go:237 +0x288
github.com/jenkinsci/kubernetes-operator/pkg/configuration/base/resources.newContainers(0xc00062e480, 0x7, 0xc0005e8ce0, 0x13)
	/workspace/pkg/configuration/base/resources/pod.go:335 +0x45
github.com/jenkinsci/kubernetes-operator/pkg/configuration/base/resources.NewJenkinsMasterPod(0xc000679800, 0xf, 0x0, 0x0, 0xc000769360, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/pkg/configuration/base/resources/pod.go:377 +0x166
github.com/jenkinsci/kubernetes-operator/pkg/configuration/base.(*JenkinsBaseConfigurationReconciler).ensureJenkinsMasterPod(0xc000014600, 0xc000128a40, 0x18, 0x0, 0x0, 0xc000769360, 0x7, 0x0, 0x0, 0x0, ...)
	/workspace/pkg/configuration/base/pod.go:158 +0x7c5
github.com/jenkinsci/kubernetes-operator/pkg/configuration/base.(*JenkinsBaseConfigurationReconciler).Reconcile(0xc000014600, 0xc00062e480, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workspace/pkg/configuration/base/reconciler.go:75 +0x1d8
github.com/jenkinsci/kubernetes-operator/controllers.(*JenkinsReconciler).reconcile(0xc000580400, 0xc000769360, 0x7, 0xc000769350, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workspace/controllers/jenkins_controller.go:252 +0xa7f
github.com/jenkinsci/kubernetes-operator/controllers.(*JenkinsReconciler).Reconcile(0xc000580400, 0x1bd5ea0, 0xc0008410e0, 0xc000769360, 0x7, 0xc000769350, 0x7, 0xc0008410e0, 0x40a23f, 0xc000030000, ...)
	/workspace/controllers/jenkins_controller.go:136 +0x187
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000090140, 0x1bd5de0, 0xc0004aca00, 0x1822f60, 0xc0006939a0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000090140, 0x1bd5de0, 0xc0004aca00, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1bd5de0, 0xc0004aca00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00078bf50)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00085df50, 0x1b9b240, 0xc000840ff0, 0xc0004aca01, 0xc0001b40c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00078bf50, 0x3b9aca00, 0x0, 0x1, 0xc0001b40c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1bd5de0, 0xc0004aca00, 0xc0007a4b70, 0x3b9aca00, 0x0, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1bd5de0, 0xc0004aca00, 0xc0007a4b70, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:195 +0x4e7
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x154d19c]

goroutine 347 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x17c4aa0, 0x260c200)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/jenkinsci/kubernetes-operator/pkg/configuration/base/resources.setLivenessAndReadinessPath(0xc00062e480)
	/workspace/pkg/configuration/base/resources/pod.go:267 +0x5c
github.com/jenkinsci/kubernetes-operator/pkg/configuration/base/resources.NewJenkinsMasterContainer(0xc00062e480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/pkg/configuration/base/resources/pod.go:237 +0x288
github.com/jenkinsci/kubernetes-operator/pkg/configuration/base/resources.newContainers(0xc00062e480, 0x7, 0xc0005e8ce0, 0x13)
	/workspace/pkg/configuration/base/resources/pod.go:335 +0x45
github.com/jenkinsci/kubernetes-operator/pkg/configuration/base/resources.NewJenkinsMasterPod(0xc000679800, 0xf, 0x0, 0x0, 0xc000769360, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/pkg/configuration/base/resources/pod.go:377 +0x166
github.com/jenkinsci/kubernetes-operator/pkg/configuration/base.(*JenkinsBaseConfigurationReconciler).ensureJenkinsMasterPod(0xc000014600, 0xc000128a40, 0x18, 0x0, 0x0, 0xc000769360, 0x7, 0x0, 0x0, 0x0, ...)
	/workspace/pkg/configuration/base/pod.go:158 +0x7c5
github.com/jenkinsci/kubernetes-operator/pkg/configuration/base.(*JenkinsBaseConfigurationReconciler).Reconcile(0xc000014600, 0xc00062e480, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workspace/pkg/configuration/base/reconciler.go:75 +0x1d8
github.com/jenkinsci/kubernetes-operator/controllers.(*JenkinsReconciler).reconcile(0xc000580400, 0xc000769360, 0x7, 0xc000769350, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workspace/controllers/jenkins_controller.go:252 +0xa7f
github.com/jenkinsci/kubernetes-operator/controllers.(*JenkinsReconciler).Reconcile(0xc000580400, 0x1bd5ea0, 0xc0008410e0, 0xc000769360, 0x7, 0xc000769350, 0x7, 0xc0008410e0, 0x40a23f, 0xc000030000, ...)
	/workspace/controllers/jenkins_controller.go:136 +0x187
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000090140, 0x1bd5de0, 0xc0004aca00, 0x1822f60, 0xc0006939a0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000090140, 0x1bd5de0, 0xc0004aca00, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1bd5de0, 0xc0004aca00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00078bf50)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00085df50, 0x1b9b240, 0xc000840ff0, 0xc0004aca01, 0xc0001b40c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00078bf50, 0x3b9aca00, 0x0, 0x1, 0xc0001b40c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1bd5de0, 0xc0004aca00, 0xc0007a4b70, 0x3b9aca00, 0x0, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1bd5de0, 0xc0004aca00, 0xc0007a4b70, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:195 +0x4e7

```

**Comment by KorusMateusz** [comment]
Hello,

Thank you for the bug report, it seems we don't handle tcp probes correctly. As a workaround, you can use an http probe on /login path

**Comment by tomvopat** [comment]
I have also tried to use exec.command in the readinessProbe instead to run a custom script, but there is the same issue. I need to allow access to jenkins-master only over HTTPS, and so this is quite an issue.

**Comment by brokenpip3** [comment]
@tomvopat this seems fixed by https://github.com/jenkinsci/kubernetes-operator/pull/735/files, could you please confirm?
