### ISSUE TITLE
Seed job fails for wrong java version in seed-job-agent

### ISSUE THREAD

**Issue by janjoerke** [jenkinsci/kubernetes-operator#761]
**Describe the bug**

Starting today, and with no conscious change, our seed job started failing because of a wrong java version in the seed-job-agent (see log below). 

To fix the issue, we tried to change the seed-job-agent to a newer version containing java 11.

```yaml
jenkins:
  seedJobAgentImage: jenkins/inbound-agent:jdk11 # Did not work
```

Unfortunately that didn't work either. The operator seems to ignore the configured seedJobAgentImage and falls back to the default image.

**Additional information**

Kubernetes version: v1.21.13-eks-84b4fe6
Jenkins Operator version: virtuslab/jenkins-operator:v0.7.1
Jenkins version: jenkins/jenkins:2.319.3-lts

**Error Logs**
```
Started
Running as SYSTEM
Building remotely on [seed-job-agent](http://jenkins.xxx.io/computer/seed-job-agent) in workspace /home/jenkins/workspace/jenkins-operator-job-dsl-seed
The recommended git tool is: NONE
java.lang.UnsupportedClassVersionError: com/trilead/ssh2/ServerHostKeyVerifier has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
	at hudson.remoting.RemoteClassLoader.loadClassFile(RemoteClassLoader.java:453)
Caused: java.lang.UnsupportedClassVersionError: Failed to load com.trilead.ssh2.ServerHostKeyVerifier
	at hudson.remoting.RemoteClassLoader.loadClassFile(RemoteClassLoader.java:455)
	at hudson.remoting.RemoteClassLoader.loadRemoteClass(RemoteClassLoader.java:295)
	at hudson.remoting.RemoteClassLoader.loadWithMultiClassLoader(RemoteClassLoader.java:264)
	at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:223)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
	at hudson.remoting.RemoteClassLoader.loadClassFile(RemoteClassLoader.java:453)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ip-172-29-12-118.eu-west-1.compute.internal/172.29.12.118:57788
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.FilePath.act(FilePath.java:1165)
		at hudson.FilePath.act(FilePath.java:1154)
		at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:140)
		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:916)
		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:847)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1297)
		at hudson.scm.SCM.checkout(SCM.java:505)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1213)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:637)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:85)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:509)
		at hudson.model.Run.execute(Run.java:1888)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:99)
		at hudson.model.Executor.run(Executor.java:432)
Caused: java.lang.UnsupportedClassVersionError: Failed to load org.jenkinsci.plugins.gitclient.verifier.AbstractJGitHostKeyVerifier
	at hudson.remoting.RemoteClassLoader.loadClassFile(RemoteClassLoader.java:455)
	at hudson.remoting.RemoteClassLoader.loadRemoteClass(RemoteClassLoader.java:287)
	at hudson.remoting.RemoteClassLoader.loadWithMultiClassLoader(RemoteClassLoader.java:264)
	at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:223)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at java.io.ObjectStreamClass.getPrivateMethod(ObjectStreamClass.java:1643)
	at java.io.ObjectStreamClass.access$1700(ObjectStreamClass.java:79)
	at java.io.ObjectStreamClass$3.run(ObjectStreamClass.java:520)
	at java.io.ObjectStreamClass$3.run(ObjectStreamClass.java:494)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:494)
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:391)
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:681)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2003)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1850)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2003)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1850)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2160)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at hudson.remoting.UserRequest.deserialize(UserRequest.java:289)
	at hudson.remoting.UserRequest.perform(UserRequest.java:189)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:122)
	at java.lang.Thread.run(Thread.java:748)
Caused: java.io.IOException: Remote call on JNLP4-connect connection from ip-172-29-12-118.eu-west-1.compute.internal/172.29.12.118:57788 failed
	at hudson.remoting.Channel.call(Channel.java:1005)
	at hudson.FilePath.act(FilePath.java:1165)
	at hudson.FilePath.act(FilePath.java:1154)
	at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:140)
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:916)
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:847)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1297)
	at hudson.scm.SCM.checkout(SCM.java:505)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1213)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:637)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:85)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:509)
	at hudson.model.Run.execute(Run.java:1888)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:99)
	at hudson.model.Executor.run(Executor.java:432)
Finished: FAILURE
```

**Comment by toabi** [comment]
We have exactly the same issue. The Jenkins CRD somehow doesn't include the seedJobAgent field although the code looks like one could overwrite it:

https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/configuration/user/seedjobs/seedjobs.go#L421-L424

But that doesn't work, as @janjoerke wrote.

My quick fix to restore a working CI/CD Pipeline is to disable the jenkins operator and manually change the seed-job deployment to use `4.10-3-jdk11` until this is fixed…

**Comment by janjoerke** [comment]
So the root cause was an update in plugin trilead-api. Reverting this plugin to 1.67.vc3938a_35172f solved the java version conflict. Nonetheless, we really need the option to set the seedJobAgent soon, or at least a new default, so that we can update plugins.

**Comment by neiljfwhite** [comment]
I've only just got around the issue by applying the latest CRD which does include the new "seedJobAgentImage"

i'm using:
```
seedJobAgentImage: jenkins/inbound-agent:4.10-3
```
https://www.jenkins.io/blog/2021/08/17/docker-images-use-jdk-11-by-default/

However whilst this fixed the problem with seed jobs I then bumped in to same issue with the agents default jnlp image, they required changing too.

However I am going to now try your suggestion @janjoerke because that is probably cleaner for the moment - so thank you

**Comment by Rohit2013** [comment]
Thanks @janjoerke , We also started facing the same issue and the suggested workaround fixed the issue.

**Comment by Harguer** [comment]
I have tried editing the seed-job deployment and updated the image as follow, and seemed worked fine:
`seedJobAgentImage: jenkins/inbound-agent:4.10-3`

But not sure if the operator will revert that change I made.

**Comment by Harguer** [comment]
Seems the issue could be fixed updating this line?
https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/configuration/user/seedjobs/seedjobs.go#L49

**Comment by Harguer** [comment]
setting up the plugin`trilead-api: 1.67.vc3938a_35172f` on plugin section is not working for me :(

**Comment by Harguer** [comment]
It is working with tag [94b1473](https://hub.docker.com/layers/virtuslab/jenkins-operator/94b1473/images/sha256-b9393e0cb0aeb43c89dae55b940bebedb656a064ef16c7c87140eb96d33930c6?context=explore), I do not know when it will be available into the latest image though

```
$ kubectl get deployment -o yaml jenkins-operator | grep -i 94b1473
        image: virtuslab/jenkins-operator:94b1473
$ kubectl get jenkins jenkins -o yaml | grep "seedJobAgentImage: jenkins"
  seedJobAgentImage: jenkins/inbound-agent:4.10-3
$ kubectl get deploy -o yaml seed-job-agent-jenkins| grep image
        image: jenkins/inbound-agent:4.10-3
        imagePullPolicy: IfNotPresent
$ kubectl get pods -o yaml seed-job-agent-jenkins-6f4ccd8757-58vhn | grep inbound-agent:
    image: jenkins/inbound-agent:4.10-3
    image: jenkins/inbound-agent:4.10-3
$
```

**Comment by zandolsi-psee** [comment]
I get always the some error with the following versions : 

- virtuslab/jenkins-operator:94b1473
- jenkins/inbound-agent:4.10-3
- jenkins/jenkins:2.361.1

**Comment by Harguer** [comment]
Hi @zandolsi-psee, i think that image has a problem right now with jenkins-operator, I tried with `jenkins/jenkins:2.361.1` version, but seed-jobs is breaking, i had to rolled-back and use this previous one `jenkins/jenkins:2.346.3-2-lts` (I opened this ticket for that issue https://github.com/jenkinsci/kubernetes-operator/issues/765) , hope that  helps.
