### ISSUE TITLE
Seed-jobs agent not launched due authorization failure

### ISSUE THREAD

**Issue by Harguer** [jenkinsci/kubernetes-operator#765]
**Describe the bug**
Note: I added more logs to this bug issue

I'm not seeing so much errors, but seems seed-jobs agent pod not launched due authorization failure.
I can't see the issue when I use previous jenkins LTS version (2.346.3)

**To Reproduce**
Install latest operator with latest jenkins lts -> 2.361.1 (2022-09-07)

**Additional information**

Kubernetes version:
tested on:
v1.21.14-eks-18ef993
v1.22.11-eks-18ef993

Jenkins Operator version: 
v0.7.1 and tag 94b1473

Add error logs about the problem here (operator logs and Kubernetes events).
No seed-job-agent-xxxxx pod is launched and the old seed-jobs pod start crashing, if it is killed same crash happens for the new pod  

Errors from Jenkins Operator pod:
```
2022-09-12T16:51:28.124Z	DEBUG	controller-jenkins	Jenkins API client set	{"cr": "jenkins"}
2022-09-12T16:51:28.139Z	DEBUG	controller-jenkins	Installed plugins '[javax-mail-api:1.6.2-5 jdk-tool:1.0 groovy:2.4 workflow-aggregator:2.6 workflow-job:1189.va_d37a_e9e4eda_ saml:1.1.8 resource-disposer:0.20 job-dsl:1.78.1 role-strategy:3.2.0 matrix-auth:2.6.11 github-api:1.303-400.v35c2d8258028 configuration-as-code:1512.vb_79d418d5fc8 kubernetes:1.31.3 aws-secrets-manager-credentials-provider:0.5.5 kubernetes-credentials-provider:0.20 command-launcher:1.2 ssh:2.6.1 git:4.10.0 envinject-api:1.199.v3ce31253ed13 workflow-api:1192.v2d0deb_19d212 lockable-resources:2.16 workflow-cps-global-lib:588.v576c103a_ff86 workflow-multibranch:716.vc692a_e52371b_ github:1.34.1 workflow-basic-steps:994.vd57e3ca_46d24 pipeline-stage-view:2.24 conditional-buildstep:1.4.2 workflow-step-api:639.v6eca_cd8c04a_a_ workflow-scm-step:400.v6b_89a_1317c9a_ cloudbees-folder:6.758.vfd75d09eea_a_1 workflow-durable-task-step:1199.v02b_9244f8064 workflow-cps:2759.v87459c4eea_ca_ workflow-support:838.va_3a_087b_4055b git-client:3.11.2 jackson2-api:2.13.3-285.vc03c0256d517 credentials:1143.vb_e8b_b_ceee347 aws-credentials:1.32 pipeline-build-step:2.18 caffeine-api:2.9.3-65.v6a_47d0f4d1fe pipeline-input-step:449.v77f0e8b_845c4 aws-java-sdk-ec2:1.12.287-357.vf82d85a_6eefd pipeline-milestone-step:101.vd572fef9d926 scm-api:621.vda_a_b_055e58f7 pipeline-stage-step:296.v5f6908f017a_5 ansicolor:1.0.1 throttle-concurrents:2.8 snakeyaml-api:1.31-84.ve43da_fb_49d0b pipeline-model-definition:2.2114.v2654ca_721309 credentials-binding:523.vd859a_4b_122e6 token-macro:308.v4f2b_ed62b_b_16 structs:324.va_f5d6774f3a_d envinject:2.4.0 authentication-tokens:1.4 kubernetes-client-api:5.11.2-182.v0f1cf4c5904e variant:59.vf075fe829ccb aws-java-sdk-ecs:1.12.287-357.vf82d85a_6eefd jakarta-mail-api:2.0.1-1 ws-cleanup:0.39 parameterized-trigger:2.42 aws-java-sdk-ecr:1.12.287-357.vf82d85a_6eefd mailer:438.v02c7f0a_12fa_4 durable-task:500.v8927d9fd99d8 pipeline-rest-api:2.24 aws-secrets-manager-secret-source:1.51.v39a_9e7452e65 script-security:1175.v4b_d517d6db_f0 matrix-project:772.v494f19991984 aws-java-sdk-ssm:1.12.287-357.vf82d85a_6eefd metrics:4.2.10-389.v93143621b_050 plain-credentials:139.ved2b_9cf7587b pipeline-groovy-lib:612.v84da_9c54906d branch-api:2.1046.v0ca_37783ecc5 apache-httpcomponents-client-4-api:4.5.13-138.v4e7d9a_7b_a_e61 aws-java-sdk:1.12.246-349.v96b_b_f7eb_a_c3c run-condition:1.5 git-server:99.va_0826a_b_cdfa_d handlebars:3.0.8 okhttp-api:4.9.3-108.v0feda04578cf momentjs:1.1.1 kubernetes-credentials:0.9.0 jsch:0.1.55.61.va_e9ee26616e7 jaxb:2.3.6-1 ssh-credentials:305.v8f4381501156 instance-identity:116.vf8f487400980 trilead-api:2.72.v2a_3236754f73 ace-editor:1.1 jakarta-activation-api:2.0.1-1 junit:1119.1121.vc43d0fc45561 display-url-api:2.3.6 sshd:3.249.v2dc2ea_416e33 pipeline-graph-analysis:195.v5812d95a_a_2f9 pipeline-model-extensions:2.2114.v2654ca_721309 pipeline-stage-tags-metadata:2.2114.v2654ca_721309 javax-activation-api:1.2.0-4 pipeline-model-api:2.2114.v2654ca_721309 echarts-api:5.3.3-1 bootstrap5-api:5.2.0-3 bouncycastle-api:2.26 plugin-util-api:2.17.0 checks-api:1.7.5 mina-sshd-api-core:2.9.1-44.v476733c11f82 popper2-api:2.11.6-1 font-awesome-api:6.1.2-1 mina-sshd-api-common:2.9.1-44.v476733c11f82 jquery3-api:3.6.0-4 aws-java-sdk-minimal:1.12.287-357.vf82d85a_6eefd aws-java-sdk-cloudformation:1.12.287-357.vf82d85a_6eefd aws-java-sdk-logs:1.12.287-357.vf82d85a_6eefd aws-java-sdk-sqs:1.12.287-357.vf82d85a_6eefd aws-java-sdk-elasticbeanstalk:1.12.287-357.vf82d85a_6eefd aws-java-sdk-iam:1.12.287-357.vf82d85a_6eefd aws-java-sdk-sns:1.12.287-357.vf82d85a_6eefd aws-java-sdk-codebuild:1.12.287-357.vf82d85a_6eefd]'	{"cr": "jenkins"}
2022-09-12T16:51:28.602Z	WARN	controller-jenkins	Reconcile loop failed: Node secret cannot be parsed
github.com/jenkinsci/kubernetes-operator/pkg/client.(*jenkins).GetNodeSecret
	/workspace/pkg/client/jenkins.go:209
github.com/jenkinsci/kubernetes-operator/pkg/configuration/user/seedjobs.(*seedJobs).createAgent
	/workspace/pkg/configuration/user/seedjobs/seedjobs.go:384
github.com/jenkinsci/kubernetes-operator/pkg/configuration/user/seedjobs.(*seedJobs).EnsureSeedJobs
	/workspace/pkg/configuration/user/seedjobs/seedjobs.go:200
github.com/jenkinsci/kubernetes-operator/pkg/configuration/user.(*reconcileUserConfiguration).ensureSeedJobs
	/workspace/pkg/configuration/user/reconcile.go:83
github.com/jenkinsci/kubernetes-operator/pkg/configuration/user.(*reconcileUserConfiguration).ReconcileOthers
	/workspace/pkg/configuration/user/reconcile.go:59
github.com/jenkinsci/kubernetes-operator/controllers.(*JenkinsReconciler).reconcile
	/workspace/controllers/jenkins_controller.go:316
github.com/jenkinsci/kubernetes-operator/controllers.(*JenkinsReconciler).Reconcile
	/workspace/controllers/jenkins_controller.go:136
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374	{"cr": "jenkins"}
github.com/go-logr/zapr.(*zapLogger).Info
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:126
github.com/jenkinsci/kubernetes-operator/controllers.(*JenkinsReconciler).Reconcile
	/workspace/controllers/jenkins_controller.go:175
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99
2022-09-12T16:51:28.602Z	DEBUG	controller-jenkins	Reconciling Jenkins	{"cr": "jenkins"}
2022-09-12T16:51:28.602Z	DEBUG	controller-jenkins	Operator credentials secret is present	{"cr": "jenkins"}
2022-09-12T16:51:28.619Z	DEBUG	controller-jenkins	Scripts config map is present	{"cr": "jenkins"}
2022-09-12T16:51:28.633Z	DEBUG	controller-jenkins	Init configuration config map is present	{"cr": "jenkins"}
2022-09-12T16:51:28.653Z	DEBUG	controller-jenkins	Base configuration config map is present	{"cr": "jenkins"}
2022-09-12T16:51:28.653Z	DEBUG	controller-jenkins	GroovyScripts Secret and ConfigMap added watched labels	{"cr": "jenkins"}
2022-09-12T16:51:28.653Z	DEBUG	controller-jenkins	ConfigurationAsCode Secret and ConfigMap added watched labels	{"cr": "jenkins"}
2022-09-12T16:51:28.653Z	DEBUG	controller-jenkins	createServiceAccount with annotations map[]	{"cr": "jenkins"}
2022-09-12T16:51:28.835Z	DEBUG	controller-jenkins	Service account, role and role binding are present	{"cr": "jenkins"}
2022-09-12T16:51:28.835Z	DEBUG	controller-jenkins	Extra role bindings are present	{"cr": "jenkins"}
2022-09-12T16:51:28.846Z	DEBUG	controller-jenkins	Jenkins HTTP Service is present	{"cr": "jenkins"}
2022-09-12T16:51:28.857Z	DEBUG	controller-jenkins	Jenkins slave Service is present	{"cr": "jenkins"}
2022-09-12T16:51:28.858Z	DEBUG	controller-jenkins	Kubernetes resources are present	{"cr": "jenkins"}
2022-09-12T16:51:28.858Z	DEBUG	controller-jenkins	Jenkins master pod is present	{"cr": "jenkins"}
2022-09-12T16:51:28.858Z	DEBUG	controller-jenkins	Jenkins master pod is ready	{"cr": "jenkins"}
2022-09-12T16:51:28.867Z	DEBUG	controller-jenkins	Jenkins API client set	{"cr": "jenkins"}
```

From jenkins logs:
```
2022-09-22 17:58:42.493+0000 [id=132]	INFO	h.TcpSlaveAgentListener$ConnectionHandler#run: Accepted JNLP4-connect connection #9 from /xxx.xx.x.xxx:xxxxx
2022-09-22 17:58:42.630+0000 [id=94]	WARNING	o.j.r.e.JnlpProtocol4Handler$Handler#onReceiveHeaders: An attempt was made to connect as seed-job-agent from ip-xxx-xx-x-xxx.us-east-2.compute.internal/xxx.xx.x.xxx:xxxxx with an incorrect secret
2022-09-22 18:00:14.537+0000 [id=141]	INFO	h.TcpSlaveAgentListener$ConnectionHandler#run: Accepted JNLP4-connect connection #10 from /xxx.xx.x.xxx:xxxxx
```

Seed jobs start crashing
```
$ k get pods
NAME                                     READY   STATUS             RESTARTS      AGE
jenkins-jenkins                          2/2     Running            0             6m57s
jenkins-operator-859bd7bc5c-mhttk        1/1     Running            0             10d
seed-job-agent-jenkins-67956b48f-tk7fl   0/1     CrashLoopBackOff   4 (58s ago)   2m37s
$
```

Logs seed jobs:
```
$ k logs seed-job-agent-jenkins-67956b48f-tk7fl
Sep 22, 2022 6:13:22 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: seed-job-agent
Sep 22, 2022 6:13:22 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Sep 22, 2022 6:13:22 PM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 4.10
Sep 22, 2022 6:13:22 PM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using /home/jenkins/agent/remoting as a remoting work directory
Sep 22, 2022 6:13:22 PM org.jenkinsci.remoting.engine.WorkDirManager setupLogging
INFO: Both error and output logs will be printed to /home/jenkins/agent/remoting
Sep 22, 2022 6:13:22 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://jenkins-operator-http-jenkins.jenkins.svc.cluster.local:443/]
Sep 22, 2022 6:13:22 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
Sep 22, 2022 6:13:22 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting TCP connection tunneling is enabled. Skipping the TCP Agent Listener Port availability check
Sep 22, 2022 6:13:22 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: jenkins-operator-slave-jenkins.jenkins.svc.cluster.local
  Agent port:    50000
  Identity:      12:54:5f:da:7f:30:79:d3:d2:c8:25:12:e0:f2:8c:e0
Sep 22, 2022 6:13:22 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Sep 22, 2022 6:13:22 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to jenkins-operator-slave-jenkins.jenkins.svc.cluster.local:50000
Sep 22, 2022 6:13:22 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP4-connect
Sep 22, 2022 6:13:22 PM org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader run
INFO: Waiting for ProtocolStack to start.
Sep 22, 2022 6:13:22 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Remote identity confirmed: 12:54:5f:da:7f:30:79:d3:d2:c8:25:12:e0:f2:8c:e0
Sep 22, 2022 6:13:22 PM org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer onRecv
INFO: [JNLP4-connect connection to jenkins-operator-slave-jenkins.jenkins.svc.cluster.local/10.100.173.121:50000] Local headers refused by remote: Authorization failure
Sep 22, 2022 6:13:22 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Authorization failure
	at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223)
	at hudson.remoting.Engine.innerRun(Engine.java:778)
	at hudson.remoting.Engine.run(Engine.java:540)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Authorization failure
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.newAbortCause(ConnectionHeadersFilterLayer.java:378)
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.onRecvClosed(ConnectionHeadersFilterLayer.java:433)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:825)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:288)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:170)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:825)
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$1500(BIONetworkLayer.java:49)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:255)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:122)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.nio.channels.ClosedChannelException
		... 7 more

Sep 22, 2022 6:13:22 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
	at hudson.remoting.Engine.onConnectionRejected(Engine.java:864)
	at hudson.remoting.Engine.innerRun(Engine.java:804)
	at hudson.remoting.Engine.run(Engine.java:540)
```

Screenshots - broken seed-jobs agent:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/42277217/189716553-0c9c2583-e7d4-490d-a7b6-722daf39b5de.png">

<img width="1833" alt="image" src="https://user-images.githubusercontent.com/42277217/189721843-e1fb1a45-6b45-4dc9-bec2-f077ba2854d2.png">

**Comment by Harguer** [comment]
Hi! I do not think is the same issue, I tried with latest inbound agent in the seed-job-agent-jenkins deployment with the jenkins crd .spec.seedJobAgentImage and got same issue. 
Also when I tried editing the seed-job-agent-jenkins deployment and updated the JENKINS_SECRET value with the string showed in my last screenshot, it worked monetarily until jenkins-operator restarts again the seed-jobs and again happens the same issue with a new JENKIN_SECRET value mismatched.  I feel something is not updating JENKIN_SECRET correctly, but i did not see anything from logs.

**Comment by chrisgrove-keysight** [comment]
I am looking to update from 2.332.4 to the latest Jenkins LTS  (2.361.2) and see the same `github.com/jenkinsci/kubernetes-operator/pkg/client.(*jenkins).GetNodeSecret` error shown above.

Kubernetes Version: v1.21.13 Provider: RKE1 
Jenkins Operator Image: virtuslab/jenkins-operator:bef796a
Jenkins Image: jenkins/jenkins:2.361.2-jdk11

**Comment by pniederlag** [comment]
see #742 for a solution, this is the very same problem

**Comment by Harguer** [comment]
I'm closing this as per the fix described here
https://github.com/jenkinsci/kubernetes-operator/issues/742
