### ISSUE TITLE
Upgraded to v0.8.0 and seeing issues with seed-job-agent

### ISSUE THREAD

**Issue by sureshdevops99** [jenkinsci/kubernetes-operator#916]
**Describe the bug**
Upgraded the jenkins-operator to v.0.8.0 and seeing the issues with seed-job-agent

jenkins-<app> pod logs:

2023-10-05 20:34:30.695+0000 [id=92]	INFO	h.TcpSlaveAgentListener$ConnectionHandler#run: Accepted JNLP4-connect connection #1 from /10.117.1.50:45428
2023-10-05 20:34:31.078+0000 [id=95]	INFO	o.j.r.p.i.ConnectionHeadersFilterLayer#onRecv: [JNLP4-connect connection from 10.117.1.50/10.117.1.50:45428] Refusing headers from remote: Unknown client name: seed-job-agent

seed-job-agent-<app> deployment.apps logs:

SEVERE: Failed to connect to http://jenkins-operator-http-mca.app.svc.cluster.local:8080/tcpSlaveAgentListener/: Connection refused (Connection refused)
java.io.IOException: Failed to connect to http://jenkins-operator-http-mca.app.svc.cluster.local:8080/tcpSlaveAgentListener/: Connection refused (Connection refused)
	at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:214)
	at hudson.remoting.Engine.innerRun(Engine.java:724)
	at hudson.remoting.Engine.run(Engine.java:540)
Caused by: java.net.ConnectException: Connection refused (Connection refused)

jenkins-operator logs:

Backup file found, proceeding
' stderr 'zstd: /*stdin*\: unexpected end of file 
tar: Child returned status 1
tar: Error is not recoverable: exiting now
'

**To Reproduce**
Steps to reproduce the behavior.

**Additional information**

Kubernetes version: 1.23.5
Jenkins Operator version: v0.8.0

Add error logs about the problem here (operator logs and Kubernetes events).

**Comment by sureshdevops99** [comment]
Any help is really appreciated!

**Comment by sureshdevops99** [comment]
I am seeing this issue recursively whenever I restart the kubernetes cluster. Assuming if I stop the cluster and start the cluster, the backup seems to be getting corrupted and I need to reprovision the jenkins again losing the jobs data and everything. I think, this might require some bugfix

**Comment by ljackiewicz** [comment]
This issue is probably duplication of #906.
